CREATE TABLE [dbo].[Recipes] (
    [RecipeId]           INT              IDENTITY (1, 1) NOT NULL,
    [Name]               NVARCHAR (255)   NOT NULL,
    [Description]        NVARCHAR (1000)  NULL,
    [RecipeSource]       NVARCHAR (255)   NOT NULL,
    [Course]             NVARCHAR (50)    NOT NULL,
    [DishType]           NVARCHAR (50)    NOT NULL,
    [Calories]           INT              NULL,
    [Fat]                INT              NULL,
    [NumberServed]       INT              NULL,
    [PrepTime]           NVARCHAR (50)    NULL,
    [CookTime]           NVARCHAR (50)    NULL,
    [EstimatedCost]      FLOAT (53)       NULL,
    [PictureFk]          INT              NULL,
    [IsViewableByPublic] BIT              CONSTRAINT [DF_Recipes_IsViewableByPublic] DEFAULT ((9)) NOT NULL,
    [ViewCount]          BIGINT           CONSTRAINT [DF_Recipes_ViewCount] DEFAULT ((0)) NOT NULL,
    [CreatedDate]        SMALLDATETIME    CONSTRAINT [DF_Recipes_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedByFk]        UNIQUEIDENTIFIER NOT NULL,
    [ModifiedDate]       SMALLDATETIME    CONSTRAINT [DF_Recipes_ModifiedDate] DEFAULT (getdate()) NOT NULL,
    [ModifiedByFk]       UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED ([RecipeId] ASC),
    CONSTRAINT [FK_Recipes_Users_CreatedBy] FOREIGN KEY ([CreatedByFk]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Recipes_Users_ModifiedBy] FOREIGN KEY ([ModifiedByFk]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Recipes_Attachments] FOREIGN KEY ([PictureFk]) REFERENCES [dbo].[Attachments] ([AttachmentId])
);
