-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #129  |  2019-01-08 23:36:33 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We just missed this one.', 255),
   LEFT(N'We just missed this one.', 500),
   N'We just missed this one.',
   '2019-01-08 23:36:33', NULL, 1, 0, 0, '2019-01-08 23:36:33', u.Id, '2019-01-08 23:36:33', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #130  |  2019-01-09 16:00:52 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Birthday Lana.', 255),
   LEFT(N'Happy Birthday Lana.', 500),
   N'Happy Birthday Lana.',
   '2019-01-09 16:00:52', NULL, 1, 0, 0, '2019-01-09 16:00:52', u.Id, '2019-01-09 16:00:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #131  |  2019-03-19 19:49:45 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Crazy hair day 1.0.', 255),
   LEFT(N'Crazy hair day 1.0.  she insisted on the bandana...stuffy pirate.', 500),
   N'Crazy hair day 1.0.  she insisted on the bandana...stuffy pirate.

![2343297622370889.jpg](/api/post-image/2343297622370889.jpg)

![2343297739037544.jpg](/api/post-image/2343297739037544.jpg)

![2343298409037477.jpg](/api/post-image/2343298409037477.jpg)',
   '2019-03-19 19:49:45', NULL, 1, 0, 0, '2019-03-19 19:49:45', u.Id, '2019-03-19 19:49:45', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #134  |  2019-09-25 16:03:42 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Milford Jr gets to ride along for crazy hair day.', 255),
   LEFT(N'Milford Jr gets to ride along for crazy hair day.', 500),
   N'Milford Jr gets to ride along for crazy hair day.

![2679719335395381.jpg](/api/post-image/2679719335395381.jpg)

![2679719322062049.jpg](/api/post-image/2679719322062049.jpg)

![2679719308728717.jpg](/api/post-image/2679719308728717.jpg)',
   '2019-09-25 16:03:42', NULL, 1, 0, 0, '2019-09-25 16:03:42', u.Id, '2019-09-25 16:03:42', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #135  |  2019-12-17 04:30:55 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'My favorite little girl just finished another trip around the sun.', 255),
   LEFT(N'My favorite little girl just finished another trip around the sun.  She was especially happy with her matching unicorn robes Shannon.', 500),
   N'My favorite little girl just finished another trip around the sun.  She was especially happy with her matching unicorn robes Shannon.

![2864233446943968.jpg](/api/post-image/2864233446943968.jpg)',
   '2019-12-17 04:30:55', NULL, 1, 0, 0, '2019-12-17 04:30:55', u.Id, '2019-12-17 04:30:55', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
