-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #4  |  2012-08-27 02:31:50 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney made it to her first Colorado State Fair in Pueblo on 8/25/2012.', 255),
   LEFT(N'Sidney made it to her first Colorado State Fair in Pueblo on 8/25/2012.  In case anyone is wondering, that orange smear around her smiling mug is carrots.', 500),
   N'Sidney made it to her first Colorado State Fair in Pueblo on 8/25/2012.  In case anyone is wondering, that orange smear around her smiling mug is carrots.

![453350288032308.jpg](/api/post-image/453350288032308.jpg)',
   '2012-08-27 02:31:50', NULL, 1, 0, 0, '2012-08-27 02:31:50', u.Id, '2012-08-27 02:31:50', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #5  |  2012-09-04 23:20:04 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'A Vote for Sidney is a vote for carrots.', 255),
   LEFT(N'A Vote for Sidney is a vote for carrots.  And who doesn''t love carrots?  Vote for Sidney as the next Gerber Baby!', 500),
   N'A Vote for Sidney is a vote for carrots.  And who doesn''t love carrots?  Vote for Sidney as the next Gerber Baby!',
   '2012-09-04 23:20:04', NULL, 1, 0, 0, '2012-09-04 23:20:04', u.Id, '2012-09-04 23:20:04', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #6  |  2012-09-06 02:47:17 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Just voted...again.', 255),
   LEFT(N'Just voted...again.  I can''t help it, she looks pretty happy.', 500),
   N'Just voted...again.  I can''t help it, she looks pretty happy.',
   '2012-09-06 02:47:17', NULL, 1, 0, 0, '2012-09-06 02:47:17', u.Id, '2012-09-06 02:47:17', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #7  |  2012-09-11 02:23:23 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Don''t forget to vote for Sidney today.', 255),
   LEFT(N'Don''t forget to vote for Sidney today.', 500),
   N'Don''t forget to vote for Sidney today.',
   '2012-09-11 02:23:23', NULL, 1, 0, 0, '2012-09-11 02:23:23', u.Id, '2012-09-11 02:23:23', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #8  |  2012-09-11 02:26:07 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Just tossing something out here so people don''t think all I do is try to win contents.', 255),
   LEFT(N'Just tossing something out here so people don''t think all I do is try to win contents.  Did I mention she is baby #447129.', 500),
   N'Just tossing something out here so people don''t think all I do is try to win contents.  Did I mention she is baby #447129.',
   '2012-09-11 02:26:07', NULL, 1, 0, 0, '2012-09-11 02:26:07', u.Id, '2012-09-11 02:26:07', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #9  |  2012-09-20 19:28:31 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Nearly ran over this guy on my lunch ride today.', 255),
   LEFT(N'Nearly ran over this guy on my lunch ride today.  Glad all I got out of the deal was a picture:)

Wikipedia tells me it is a prairie rattlesnake.   http://en.wikipedia.org/wiki/Crotalus_virdis', 500),
   N'Nearly ran over this guy on my lunch ride today.  Glad all I got out of the deal was a picture:)

Wikipedia tells me it is a prairie rattlesnake.   http://en.wikipedia.org/wiki/Crotalus_virdis

![462604413773562.jpg](/api/post-image/462604413773562.jpg)',
   '2012-09-20 19:28:31', NULL, 1, 0, 0, '2012-09-20 19:28:31', u.Id, '2012-09-20 19:28:31', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #10  |  2012-09-24 01:20:48 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Another day, another rattler.', 255),
   LEFT(N'Another day, another rattler.  Perhaps I should find another place to ride my bike.', 500),
   N'Another day, another rattler.  Perhaps I should find another place to ride my bike.

![463781693655834.jpg](/api/post-image/463781693655834.jpg)',
   '2012-09-24 01:20:48', NULL, 1, 0, 0, '2012-09-24 01:20:48', u.Id, '2012-09-24 01:20:48', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #11  |  2012-10-27 16:35:18 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Who doesn''t like the corn maze', 255),
   LEFT(N'Who doesn''t like the corn maze', 500),
   N'Who doesn''t like the corn maze',
   '2012-10-27 16:35:18', NULL, 1, 0, 0, '2012-10-27 16:35:18', u.Id, '2012-10-27 16:35:18', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #12  |  2012-11-06 15:48:35 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Civic duty - Check.', 255),
   LEFT(N'Civic duty - Check.', 500),
   N'Civic duty - Check.

![481165285250808.jpg](/api/post-image/481165285250808.jpg)',
   '2012-11-06 15:48:35', NULL, 1, 0, 0, '2012-11-06 15:48:35', u.Id, '2012-11-06 15:48:35', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #13  |  2012-11-06 15:49:52 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'While we are waiting for election results....', 255),
   LEFT(N'While we are waiting for election results....', 500),
   N'While we are waiting for election results....',
   '2012-11-06 15:49:52', NULL, 1, 0, 0, '2012-11-06 15:49:52', u.Id, '2012-11-06 15:49:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #14  |  2012-11-14 18:01:53 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Don''t punch me bro!', 255),
   LEFT(N'Don''t punch me bro!  Interesting FYI: Secretary of the Interior is eight in the line of succession for the pres.  How can he possibly oversee our national parks and blm but he can''t handle a few questions?  

http://protectmustangs.org/?tag=dave-phillips', 500),
   N'Don''t punch me bro!  Interesting FYI: Secretary of the Interior is eight in the line of succession for the pres.  How can he possibly oversee our national parks and blm but he can''t handle a few questions?  

http://protectmustangs.org/?tag=dave-phillips',
   '2012-11-14 18:01:53', NULL, 1, 0, 0, '2012-11-14 18:01:53', u.Id, '2012-11-14 18:01:53', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
