-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #46  |  2016-01-07 01:57:02 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Who knew being encased in a big honkin'' bubble was so much fun.', 255),
   LEFT(N'Who knew being encased in a big honkin'' bubble was so much fun.  Love the new children''s museum in Denver.', 500),
   N'Who knew being encased in a big honkin'' bubble was so much fun.  Love the new children''s museum in Denver.

![1075412859159378.jpg](/api/post-image/1075412859159378.jpg)',
   '2016-01-07 01:57:02', NULL, 1, 0, 0, '2016-01-07 01:57:02', u.Id, '2016-01-07 01:57:02', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #47  |  2016-01-07 02:00:20 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sid''s first ski lesson of the season.', 255),
   LEFT(N'Sid''s first ski lesson of the season.  She  is about three lessons from passing me on the mountain.', 500),
   N'Sid''s first ski lesson of the season.  She  is about three lessons from passing me on the mountain.

![1075414529159211.jpg](/api/post-image/1075414529159211.jpg)',
   '2016-01-07 02:00:20', NULL, 1, 0, 0, '2016-01-07 02:00:20', u.Id, '2016-01-07 02:00:20', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #48  |  2016-01-28 00:36:31 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney is picking up skiing pretty good after 4 lessons.', 255),
   LEFT(N'Sidney is picking up skiing pretty good after 4 lessons. She has 4 more in February.   Maybe they will get her on the bumps:)', 500),
   N'Sidney is picking up skiing pretty good after 4 lessons. She has 4 more in February.   Maybe they will get her on the bumps:)

*(1 video(s) from this post not yet imported)*',
   '2016-01-28 00:36:31', NULL, 1, 0, 0, '2016-01-28 00:36:31', u.Id, '2016-01-28 00:36:31', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #49  |  2016-01-29 02:49:28 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney jumped at the chance to pick up a fly rod at the international sportsman''s expo.', 255),
   LEFT(N'Sidney jumped at the chance to pick up a fly rod at the international sportsman''s expo.  Not too shabby for her first cast.', 500),
   N'Sidney jumped at the chance to pick up a fly rod at the international sportsman''s expo.  Not too shabby for her first cast.

*(1 video(s) from this post not yet imported)*',
   '2016-01-29 02:49:28', NULL, 1, 0, 0, '2016-01-29 02:49:28', u.Id, '2016-01-29 02:49:28', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #50  |  2016-02-07 02:01:33 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Do you wanna be a snowman?', 255),
   LEFT(N'Do you wanna be a snowman?  We had a great day building a Grinch snowman in between toboggan runs down our backyard.', 500),
   N'Do you wanna be a snowman?  We had a great day building a Grinch snowman in between toboggan runs down our backyard.

![1093205817380082.jpg](/api/post-image/1093205817380082.jpg)

![1093206577380006.jpg](/api/post-image/1093206577380006.jpg)',
   '2016-02-07 02:01:33', NULL, 1, 0, 0, '2016-02-07 02:01:33', u.Id, '2016-02-07 02:01:33', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #51  |  2016-04-03 00:58:16 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney Hazeltine got her first ski day in at steamboat today.', 255),
   LEFT(N'Sidney Hazeltine got her first ski day in at steamboat today.  I also managed to sneak in a few turns after she tuckered herself out . Thanks Jeri Hazeltine', 500),
   N'Sidney Hazeltine got her first ski day in at steamboat today.  I also managed to sneak in a few turns after she tuckered herself out . Thanks Jeri Hazeltine

![1133474540019876.jpg](/api/post-image/1133474540019876.jpg)

![1133474580019872.jpg](/api/post-image/1133474580019872.jpg)

![1133474630019867.jpg](/api/post-image/1133474630019867.jpg)',
   '2016-04-03 00:58:16', NULL, 1, 0, 0, '2016-04-03 00:58:16', u.Id, '2016-04-03 00:58:16', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #52  |  2016-04-13 02:48:41 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney and I were playing a rousing game of rock, paper, scissors, lizard, spock.', 255),
   LEFT(N'Sidney and I were playing a rousing game of rock, paper, scissors, lizard, spock.  She was winning most rolls and uttered "Smalls is killing you".  Funny twist on a famous quote from what movie?', 500),
   N'Sidney and I were playing a rousing game of rock, paper, scissors, lizard, spock.  She was winning most rolls and uttered "Smalls is killing you".  Funny twist on a famous quote from what movie?',
   '2016-04-13 02:48:41', NULL, 1, 0, 0, '2016-04-13 02:48:41', u.Id, '2016-04-13 02:48:41', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #53  |  2016-04-20 00:40:31 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Wonder woman is taming one last frozen bad guy for the season.', 255),
   LEFT(N'Wonder woman is taming one last frozen bad guy for the season.', 500),
   N'Wonder woman is taming one last frozen bad guy for the season.

![1144550862245577.jpg](/api/post-image/1144550862245577.jpg)

![1144550895578907.jpg](/api/post-image/1144550895578907.jpg)',
   '2016-04-20 00:40:31', NULL, 1, 0, 0, '2016-04-20 00:40:31', u.Id, '2016-04-20 00:40:31', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #54  |  2016-04-30 20:06:41 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney got to meet Jake the Snake, Miles, and a couple Denver Bronco Cheerleaders today at Mary Jane before they announced today''s draft picks.  Miles snuck in a kiss on her cheek and made her day.  #draftday3 #maryjaneterritory', 255),
   LEFT(N'Sidney got to meet Jake the Snake, Miles, and a couple Denver Bronco Cheerleaders today at Mary Jane before they announced today''s draft picks.  Miles snuck in a kiss on her cheek and made her day.  #draftday3 #maryjaneterritory', 500),
   N'Sidney got to meet Jake the Snake, Miles, and a couple Denver Bronco Cheerleaders today at Mary Jane before they announced today''s draft picks.  Miles snuck in a kiss on her cheek and made her day.  #draftday3 #maryjaneterritory

![1151610598206270.jpg](/api/post-image/1151610598206270.jpg)',
   '2016-04-30 20:06:41', NULL, 1, 0, 0, '2016-04-30 20:06:41', u.Id, '2016-04-30 20:06:41', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #55  |  2016-05-02 01:15:36 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'So we thought winter was over.', 255),
   LEFT(N'So we thought winter was over.  It is may after all.  From the expression on Sidney''s face, she has met her quota of cold and frozen characters for the season.  Viva wintertime!', 500),
   N'So we thought winter was over.  It is may after all.  From the expression on Sidney''s face, she has met her quota of cold and frozen characters for the season.  Viva wintertime!

![1152372321463431.jpg](/api/post-image/1152372321463431.jpg)

![1152372348130095.jpg](/api/post-image/1152372348130095.jpg)

![1152372381463425.jpg](/api/post-image/1152372381463425.jpg)',
   '2016-05-02 01:15:36', NULL, 1, 0, 0, '2016-05-02 01:15:36', u.Id, '2016-05-02 01:15:36', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #56  |  2016-05-20 00:58:39 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Birthday Pops.', 255),
   LEFT(N'Happy Birthday Pops.  It was good talking to you today and I am really looking forward to seeing you two next week.', 500),
   N'Happy Birthday Pops.  It was good talking to you today and I am really looking forward to seeing you two next week.',
   '2016-05-20 00:58:39', NULL, 1, 0, 0, '2016-05-20 00:58:39', u.Id, '2016-05-20 00:58:39', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #57  |  2016-06-02 23:27:33 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Looking to butterfly a turkey for the smoker.', 255),
   LEFT(N'Looking to butterfly a turkey for the smoker.  These guys have not failed me on any of my other bbq adventures.', 500),
   N'Looking to butterfly a turkey for the smoker.  These guys have not failed me on any of my other bbq adventures.',
   '2016-06-02 23:27:33', NULL, 1, 0, 0, '2016-06-02 23:27:33', u.Id, '2016-06-02 23:27:33', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #58  |  2016-06-03 22:53:44 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Here is an opportunity that will likely only ever come around once in our lifetime.', 255),
   LEFT(N'Here is an opportunity that will likely only ever come around once in our lifetime.  Are you up for it @[100000672411712:2048:Jeri]?', 500),
   N'Here is an opportunity that will likely only ever come around once in our lifetime.  Are you up for it @[100000672411712:2048:Jeri]?',
   '2016-06-03 22:53:44', NULL, 1, 0, 0, '2016-06-03 22:53:44', u.Id, '2016-06-03 22:53:44', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #59  |  2016-06-22 16:51:01 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Our daughter is progressing at a very fast rate, however, we neglected to show her the proper way to load a fresh roll on the spool:)', 255),
   LEFT(N'Our daughter is progressing at a very fast rate, however, we neglected to show her the proper way to load a fresh roll on the spool:)', 500),
   N'Our daughter is progressing at a very fast rate, however, we neglected to show her the proper way to load a fresh roll on the spool:)

![1186215228079140.jpg](/api/post-image/1186215228079140.jpg)',
   '2016-06-22 16:51:01', NULL, 1, 0, 0, '2016-06-22 16:51:01', u.Id, '2016-06-22 16:51:01', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #60  |  2016-07-30 00:55:39 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Of all the times to leave your Junior Mints at home.', 255),
   LEFT(N'Of all the times to leave your Junior Mints at home.  Jeri and I are in the Pikes Peak Center balcony waiting for Jerry Seinfeld to take the stage.', 500),
   N'Of all the times to leave your Junior Mints at home.  Jeri and I are in the Pikes Peak Center balcony waiting for Jerry Seinfeld to take the stage.

![1212146258819370.jpg](/api/post-image/1212146258819370.jpg)',
   '2016-07-30 00:55:39', NULL, 1, 0, 0, '2016-07-30 00:55:39', u.Id, '2016-07-30 00:55:39', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #61  |  2016-08-07 01:53:53 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'She has a pretty big smile.', 255),
   LEFT(N'She has a pretty big smile.  Sidney was pretty happy too.', 500),
   N'She has a pretty big smile.  Sidney was pretty happy too.

![1218160891551240.jpg](/api/post-image/1218160891551240.jpg)',
   '2016-08-07 01:53:53', NULL, 1, 0, 0, '2016-08-07 01:53:53', u.Id, '2016-08-07 01:53:53', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #62  |  2016-09-11 16:29:34 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Our 2016 family vacation in @[100064819747564:2048:Walt Disney World].', 255),
   LEFT(N'Our 2016 family vacation in @[100064819747564:2048:Walt Disney World].', 500),
   N'Our 2016 family vacation in @[100064819747564:2048:Walt Disney World].',
   '2016-09-11 16:29:34', NULL, 1, 0, 0, '2016-09-11 16:29:34', u.Id, '2016-09-11 16:29:34', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #63  |  2016-09-11 20:26:42 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'2016 Hazeltine Family Vacation at @[100064819747564:2048:Walt Disney World]', 255),
   LEFT(N'2016 Hazeltine Family Vacation at @[100064819747564:2048:Walt Disney World]', 500),
   N'2016 Hazeltine Family Vacation at @[100064819747564:2048:Walt Disney World]',
   '2016-09-11 20:26:42', NULL, 1, 0, 0, '2016-09-11 20:26:42', u.Id, '2016-09-11 20:26:42', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #64  |  2016-10-01 14:29:43 UTC  |  4 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Balloon Fiesta 2016 in Albuquerque with my two favorite ladies:)', 255),
   LEFT(N'Balloon Fiesta 2016 in Albuquerque with my two favorite ladies:)', 500),
   N'Balloon Fiesta 2016 in Albuquerque with my two favorite ladies:)

![1267495499951112.jpg](/api/post-image/1267495499951112.jpg)

![1267804843253511.jpg](/api/post-image/1267804843253511.jpg)

![1267804859920176.jpg](/api/post-image/1267804859920176.jpg)

![1267804853253510.jpg](/api/post-image/1267804853253510.jpg)',
   '2016-10-01 14:29:43', NULL, 1, 0, 0, '2016-10-01 14:29:43', u.Id, '2016-10-01 14:29:43', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #65  |  2016-10-07 14:51:17 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'since you are excited about  baking season..this looks like a pretty good option.', 255),
   LEFT(N'since you are excited about  baking season..this looks like a pretty good option.', 500),
   N'since you are excited about  baking season..this looks like a pretty good option.',
   '2016-10-07 14:51:17', NULL, 1, 0, 0, '2016-10-07 14:51:17', u.Id, '2016-10-07 14:51:17', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #66  |  2016-10-29 00:51:38 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'2016 solo elk hunt.', 255),
   LEFT(N'2016 solo elk hunt.', 500),
   N'2016 solo elk hunt.

![1293673883999940.jpg](/api/post-image/1293673883999940.jpg)

![1293673910666604.jpg](/api/post-image/1293673910666604.jpg)',
   '2016-10-29 00:51:38', NULL, 1, 0, 0, '2016-10-29 00:51:38', u.Id, '2016-10-29 00:51:38', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #67  |  2016-11-22 02:18:44 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Watchin'' doc McStuffins with Sid.', 255),
   LEFT(N'Watchin'' doc McStuffins with Sid.  The elf just discovered a broken toy.  She is vested:). #disney', 500),
   N'Watchin'' doc McStuffins with Sid.  The elf just discovered a broken toy.  She is vested:). #disney

![1317057281661600.jpg](/api/post-image/1317057281661600.jpg)',
   '2016-11-22 02:18:44', NULL, 1, 0, 0, '2016-11-22 02:18:44', u.Id, '2016-11-22 02:18:44', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #68  |  2016-11-24 21:02:07 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy turkey day!', 255),
   LEFT(N'Happy turkey day!', 500),
   N'Happy turkey day!

![1319756901391638.jpg](/api/post-image/1319756901391638.jpg)',
   '2016-11-24 21:02:07', NULL, 1, 0, 0, '2016-11-24 21:02:07', u.Id, '2016-11-24 21:02:07', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #69  |  2016-12-08 15:26:17 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'I could have used these onion goggles the other day.', 255),
   LEFT(N'I could have used these onion goggles the other day.', 500),
   N'I could have used these onion goggles the other day.',
   '2016-12-08 15:26:17', NULL, 1, 0, 0, '2016-12-08 15:26:17', u.Id, '2016-12-08 15:26:17', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #70  |  2016-12-11 15:39:06 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'First ski day at Copper Mountain for 2016 season', 255),
   LEFT(N'First ski day at Copper Mountain for 2016 season', 500),
   N'First ski day at Copper Mountain for 2016 season

![1341620829205245.jpg](/api/post-image/1341620829205245.jpg)',
   '2016-12-11 15:39:06', NULL, 1, 0, 0, '2016-12-11 15:39:06', u.Id, '2016-12-11 15:39:06', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
