-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #163  |  2024-02-15 02:40:25 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Wagyu.it''s what''s for dinner.', 255),
   LEFT(N'Wagyu.it''s what''s for dinner.  Wish every cow had massages and steins of their (my😁) favorite hoppy beverage.', 500),
   N'Wagyu.it''s what''s for dinner.  Wish every cow had massages and steins of their (my😁) favorite hoppy beverage.

![7492777487422851.jpg](/api/post-image/7492777487422851.jpg)

![7492777870756146.jpg](/api/post-image/7492777870756146.jpg)',
   '2024-02-15 02:40:25', NULL, 1, 0, 0, '2024-02-15 02:40:25', u.Id, '2024-02-15 02:40:25', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #180  |  2024-11-01 19:59:54 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Happy Birthday, Shannon!', 255),
   LEFT(N'Happy Happy Birthday, Shannon! 🎉🎊', 500),
   N'Happy Happy Birthday, Shannon! 🎉🎊',
   '2024-11-01 19:59:54', NULL, 1, 0, 0, '2024-11-01 19:59:54', u.Id, '2024-11-01 19:59:54', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
