-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #141  |  2021-09-27 20:36:02 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'I believe we saw this Jeep on the way home Sunday', 255),
   LEFT(N'I believe we saw this Jeep on the way home Sunday', 500),
   N'I believe we saw this Jeep on the way home Sunday',
   '2021-09-27 20:36:02', NULL, 1, 0, 0, '2021-09-27 20:36:02', u.Id, '2021-09-27 20:36:02', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #142  |  2021-10-01 21:06:47 UTC  |  4 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Seems like this was more than 5 years ago.', 255),
   LEFT(N'Seems like this was more than 5 years ago.', 500),
   N'Seems like this was more than 5 years ago.

![1267495499951112.jpg](/api/post-image/1267495499951112.jpg)

![1267804843253511.jpg](/api/post-image/1267804843253511.jpg)

![1267804859920176.jpg](/api/post-image/1267804859920176.jpg)

![1267804853253510.jpg](/api/post-image/1267804853253510.jpg)',
   '2021-10-01 21:06:47', NULL, 1, 0, 0, '2021-10-01 21:06:47', u.Id, '2021-10-01 21:06:47', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #143  |  2021-12-24 16:50:51 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Yet another reason to keep Metallica on your playlist', 255),
   LEFT(N'Yet another reason to keep Metallica on your playlist', 500),
   N'Yet another reason to keep Metallica on your playlist',
   '2021-12-24 16:50:51', NULL, 1, 0, 0, '2021-12-24 16:50:51', u.Id, '2021-12-24 16:50:51', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
