-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #37  |  2015-02-13 04:03:17 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Thank you Shannon.', 255),
   LEFT(N'Thank you Shannon.   As you can see, Sidney is somewhat familiar with Frozen.', 500),
   N'Thank you Shannon.   As you can see, Sidney is somewhat familiar with Frozen.

*(1 video(s) from this post not yet imported)*',
   '2015-02-13 04:03:17', NULL, 1, 0, 0, '2015-02-13 04:03:17', u.Id, '2015-02-13 04:03:17', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #38  |  2015-02-27 19:25:10 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Looks like blue fundip could be a bit on the tart side.', 255),
   LEFT(N'Looks like blue fundip could be a bit on the tart side.', 500),
   N'Looks like blue fundip could be a bit on the tart side.

![908475062519826.jpg](/api/post-image/908475062519826.jpg)',
   '2015-02-27 19:25:10', NULL, 1, 0, 0, '2015-02-27 19:25:10', u.Id, '2015-02-27 19:25:10', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #39  |  2015-02-27 19:36:45 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney is getting big enough now to dress herself.', 255),
   LEFT(N'Sidney is getting big enough now to dress herself.  I just wonder if she put her pants on backwards just to make me feel useful', 500),
   N'Sidney is getting big enough now to dress herself.  I just wonder if she put her pants on backwards just to make me feel useful

![908477079186291.jpg](/api/post-image/908477079186291.jpg)',
   '2015-02-27 19:36:45', NULL, 1, 0, 0, '2015-02-27 19:36:45', u.Id, '2015-02-27 19:36:45', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #40  |  2015-03-20 01:51:50 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Time to get your preference points in order.', 255),
   LEFT(N'Time to get your preference points in order.', 500),
   N'Time to get your preference points in order.',
   '2015-03-20 01:51:50', NULL, 1, 0, 0, '2015-03-20 01:51:50', u.Id, '2015-03-20 01:51:50', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #41  |  2015-03-30 00:26:23 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sean - we went to estes park this weekend and sid stumbled into one of your favorite Colorado haunts - the taffy shop.', 255),
   LEFT(N'Sean - we went to estes park this weekend and sid stumbled into one of your favorite Colorado haunts - the taffy shop.', 500),
   N'Sean - we went to estes park this weekend and sid stumbled into one of your favorite Colorado haunts - the taffy shop.

![925166957517303.jpg](/api/post-image/925166957517303.jpg)',
   '2015-03-30 00:26:23', NULL, 1, 0, 0, '2015-03-30 00:26:23', u.Id, '2015-03-30 00:26:23', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #42  |  2015-04-17 17:35:39 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney’s annual spring time snowman is standing tall.', 255),
   LEFT(N'Sidney’s annual spring time snowman is standing tall.  You would never guess that just yesterday (4/16/2015) our painters finished painting our house..yes the outside.   This picture was snapped by our neighbor.', 500),
   N'Sidney’s annual spring time snowman is standing tall.  You would never guess that just yesterday (4/16/2015) our painters finished painting our house..yes the outside.   This picture was snapped by our neighbor.

![934997659867566.jpg](/api/post-image/934997659867566.jpg)',
   '2015-04-17 17:35:39', NULL, 1, 0, 0, '2015-04-17 17:35:39', u.Id, '2015-04-17 17:35:39', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #43  |  2015-07-12 23:21:19 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s first away from the backyard camping trip was quite a hit at11 mile reservoir.', 255),
   LEFT(N'Sidney''s first away from the backyard camping trip was quite a hit at11 mile reservoir.  She liked peeling the corn more than eating it.  She also loved setting up the tent and sleeping in it almost as much as she likes her princess tent(thanks aunt Shannon).', 500),
   N'Sidney''s first away from the backyard camping trip was quite a hit at11 mile reservoir.  She liked peeling the corn more than eating it.  She also loved setting up the tent and sleeping in it almost as much as she likes her princess tent(thanks aunt Shannon).

![983364995030832.jpg](/api/post-image/983364995030832.jpg)',
   '2015-07-12 23:21:19', NULL, 1, 0, 0, '2015-07-12 23:21:19', u.Id, '2015-07-12 23:21:19', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #44  |  2015-08-07 18:48:17 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Today is the anniversary of the passing of Axel Roerig.', 255),
   LEFT(N'Today is the anniversary of the passing of Axel Roerig.  He was without a doubt, one of the best people I have ever had the pleasure of knowing.

Most people knew him as an adventurous rock climber that lived as close to a nomad as anyone over his last couple years.  I remember him as the guy that would go ice climbing, even though he hated cold fingers.  He would help me figure out the backwards wiring in my house, even if it meant we nearly burnt the place down.  He was more than willing to he', 500),
   N'Today is the anniversary of the passing of Axel Roerig.  He was without a doubt, one of the best people I have ever had the pleasure of knowing.

Most people knew him as an adventurous rock climber that lived as close to a nomad as anyone over his last couple years.  I remember him as the guy that would go ice climbing, even though he hated cold fingers.  He would help me figure out the backwards wiring in my house, even if it meant we nearly burnt the place down.  He was more than willing to help me move a heavy refrigerator, hang drywall, or lend a hand while I was landscaping.  More than anything, he was a great friend and he is missed. 

Thanks to the folks that keep his memories around.  I found a couple links, but if anyone else has any, please pass them along.

http://www.rockclimbing.com/photos/Trad/Axel_Roerig_on_4X4_67962.html

http://archives.wcexaminer.com/index.php/2006/08/16/thomas-roerig/

https://ablack.wordpress.com/2006/08/12/trajic-passing-of-thomas-axel-roerig/

![999439450090053.jpg](/api/post-image/999439450090053.jpg)

![999442013423130.jpg](/api/post-image/999442013423130.jpg)',
   '2015-08-07 18:48:17', NULL, 1, 0, 0, '2015-08-07 18:48:17', u.Id, '2015-08-07 18:48:17', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #45  |  2015-11-15 05:19:26 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'November in Colorado.', 255),
   LEFT(N'November in Colorado.  Got to love it.', 500),
   N'November in Colorado.  Got to love it.

![1048534201847244.jpg](/api/post-image/1048534201847244.jpg)',
   '2015-11-15 05:19:26', NULL, 1, 0, 0, '2015-11-15 05:19:26', u.Id, '2015-11-15 05:19:26', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
