-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #71  |  2017-01-13 03:09:36 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Nothing says epic powder day like the skiing pickle.', 255),
   LEFT(N'Nothing says epic powder day like the skiing pickle.', 500),
   N'Nothing says epic powder day like the skiing pickle.

![1378090988891562.jpg](/api/post-image/1378090988891562.jpg)

![1378091012224893.jpg](/api/post-image/1378091012224893.jpg)

![1378091045558223.jpg](/api/post-image/1378091045558223.jpg)',
   '2017-01-13 03:09:36', NULL, 1, 0, 0, '2017-01-13 03:09:36', u.Id, '2017-01-13 03:09:36', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #73  |  2017-02-04 03:45:03 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s ice cream cup qualifier.', 255),
   LEFT(N'Sidney''s ice cream cup qualifier.  Look at her go.', 500),
   N'Sidney''s ice cream cup qualifier.  Look at her go.

*(1 video(s) from this post not yet imported)*',
   '2017-02-04 03:45:03', NULL, 1, 0, 0, '2017-02-04 03:45:03', u.Id, '2017-02-04 03:45:03', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #74  |  2017-02-25 20:58:21 UTC  |  5 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'A great day sledding - came to an abrupt stop.', 255),
   LEFT(N'A great day sledding - came to an abrupt stop.  Sidney and I were heading down to attempt an Evil Knievel jump over the ditch when we were rudely interrupted by a pesky stump that tried to eat our sled. We had enough speed to clear the ditch...If we could have got there. ⚡ 

Sid was riding on my lap and made it out unschathed.  Thanks for the assist Jeri.   Given my luck with sleds, perhaps I should stick to safe sports like ice climbing💥💫', 500),
   N'A great day sledding - came to an abrupt stop.  Sidney and I were heading down to attempt an Evil Knievel jump over the ditch when we were rudely interrupted by a pesky stump that tried to eat our sled. We had enough speed to clear the ditch...If we could have got there. ⚡ 

Sid was riding on my lap and made it out unschathed.  Thanks for the assist Jeri.   Given my luck with sleds, perhaps I should stick to safe sports like ice climbing💥💫

![1421520301215297.jpg](/api/post-image/1421520301215297.jpg)

![1421520314548629.jpg](/api/post-image/1421520314548629.jpg)

![1421520354548625.jpg](/api/post-image/1421520354548625.jpg)

![1421520291215298.jpg](/api/post-image/1421520291215298.jpg)

![1421520304548630.jpg](/api/post-image/1421520304548630.jpg)',
   '2017-02-25 20:58:21', NULL, 1, 0, 0, '2017-02-25 20:58:21', u.Id, '2017-02-25 20:58:21', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #75  |  2017-03-08 02:37:37 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s movie from her ice cream cup at copper to celebrate all her mad skills.', 255),
   LEFT(N'Sidney''s movie from her ice cream cup at copper to celebrate all her mad skills.', 500),
   N'Sidney''s movie from her ice cream cup at copper to celebrate all her mad skills.

*(1 video(s) from this post not yet imported)*',
   '2017-03-08 02:37:37', NULL, 1, 0, 0, '2017-03-08 02:37:37', u.Id, '2017-03-08 02:37:37', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #76  |  2017-03-13 02:03:19 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'You ever going to grab a rifle and go elk hunting with me?', 255),
   LEFT(N'You ever going to grab a rifle and go elk hunting with me?', 500),
   N'You ever going to grab a rifle and go elk hunting with me?',
   '2017-03-13 02:03:19', NULL, 1, 0, 0, '2017-03-13 02:03:19', u.Id, '2017-03-13 02:03:19', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #77  |  2017-03-15 13:37:03 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Found a site that lets you dig through statistics from last year to help predict what to expect in the draw this year.  I set the filter with 7 non-resident points for muzzleloader as a guess at @[100008005298732:2048:Mark]''s current number.', 255),
   LEFT(N'Found a site that lets you dig through statistics from last year to help predict what to expect in the draw this year.  I set the filter with 7 non-resident points for muzzleloader as a guess at @[100008005298732:2048:Mark]''s current number.', 500),
   N'Found a site that lets you dig through statistics from last year to help predict what to expect in the draw this year.  I set the filter with 7 non-resident points for muzzleloader as a guess at @[100008005298732:2048:Mark]''s current number.',
   '2017-03-15 13:37:03', NULL, 1, 0, 0, '2017-03-15 13:37:03', u.Id, '2017-03-15 13:37:03', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #78  |  2017-03-23 18:12:02 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Lunch on the top of the world.', 255),
   LEFT(N'Lunch on the top of the world. Not really the top, but close enough.', 500),
   N'Lunch on the top of the world. Not really the top, but close enough.

![1446705202030140.jpg](/api/post-image/1446705202030140.jpg)',
   '2017-03-23 18:12:02', NULL, 1, 0, 0, '2017-03-23 18:12:02', u.Id, '2017-03-23 18:12:02', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #80  |  2017-05-05 14:35:29 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Cinco de Mayo!', 255),
   LEFT(N'Happy Cinco de Mayo!', 500),
   N'Happy Cinco de Mayo!',
   '2017-05-05 14:35:29', NULL, 1, 0, 0, '2017-05-05 14:35:29', u.Id, '2017-05-05 14:35:29', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #81  |  2017-05-19 14:51:57 UTC  |  5 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Birthday Pops!', 255),
   LEFT(N'Happy Birthday Pops!  Here is to many more hunting trips.', 500),
   N'Happy Birthday Pops!  Here is to many more hunting trips.

![1512949392072387.jpg](/api/post-image/1512949392072387.jpg)

![1512948725405787.jpg](/api/post-image/1512948725405787.jpg)

![1512953058738687.jpg](/api/post-image/1512953058738687.jpg)

![1512956585405001.jpg](/api/post-image/1512956585405001.jpg)

![1512960425404617.jpg](/api/post-image/1512960425404617.jpg)',
   '2017-05-19 14:51:57', NULL, 1, 0, 0, '2017-05-19 14:51:57', u.Id, '2017-05-19 14:51:57', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #82  |  2017-06-09 02:48:41 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We have been in our new home for a week now and the locals are proving to be quite entertaining.', 255),
   LEFT(N'We have been in our new home for a week now and the locals are proving to be quite entertaining.  I can''t believe we waited so long to move to Evergreen.', 500),
   N'We have been in our new home for a week now and the locals are proving to be quite entertaining.  I can''t believe we waited so long to move to Evergreen.

*(1 video(s) from this post not yet imported)*',
   '2017-06-09 02:48:41', NULL, 1, 0, 0, '2017-06-09 02:48:41', u.Id, '2017-06-09 02:48:41', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #83  |  2017-06-24 21:04:40 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Did someone say bacon?  It was Sidney.', 255),
   LEFT(N'Did someone say bacon?  It was Sidney.  We are at her favorite "festibal" in the world,. Keystone''s annual bacon festival.', 500),
   N'Did someone say bacon?  It was Sidney.  We are at her favorite "festibal" in the world,. Keystone''s annual bacon festival.

![1555285574505435.jpg](/api/post-image/1555285574505435.jpg)',
   '2017-06-24 21:04:40', NULL, 1, 0, 0, '2017-06-24 21:04:40', u.Id, '2017-06-24 21:04:40', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #84  |  2017-07-02 01:10:29 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Go Rapids!!!', 255),
   LEFT(N'Go Rapids!!!', 500),
   N'Go Rapids!!!

![1564263620274297.jpg](/api/post-image/1564263620274297.jpg)',
   '2017-07-02 01:10:29', NULL, 1, 0, 0, '2017-07-02 01:10:29', u.Id, '2017-07-02 01:10:29', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #85  |  2017-08-08 14:17:31 UTC  |  0 photo(s) linked, 2 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We had a mama and a couple cubs swing by just before midnight.', 255),
   LEFT(N'We had a mama and a couple cubs swing by just before midnight.', 500),
   N'We had a mama and a couple cubs swing by just before midnight.

*(2 video(s) from this post not yet imported)*',
   '2017-08-08 14:17:31', NULL, 1, 0, 0, '2017-08-08 14:17:31', u.Id, '2017-08-08 14:17:31', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #86  |  2017-08-17 15:57:23 UTC  |  5 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Today is Sidney''s first day of 1st Grade at Bergen - not the kind of Bergen''s that eat trolls:).', 255),
   LEFT(N'Today is Sidney''s first day of 1st Grade at Bergen - not the kind of Bergen''s that eat trolls:).  She was so excited to get there that she talked me into leaving 10 minutes early.   Thanks for walking me through the pig tails, getting all her school supplies, and packing her lunch then night before Jeri.', 500),
   N'Today is Sidney''s first day of 1st Grade at Bergen - not the kind of Bergen''s that eat trolls:).  She was so excited to get there that she talked me into leaving 10 minutes early.   Thanks for walking me through the pig tails, getting all her school supplies, and packing her lunch then night before Jeri.

![1614179885282670.jpg](/api/post-image/1614179885282670.jpg)

![1614179888616003.jpg](/api/post-image/1614179888616003.jpg)

![1614179891949336.jpg](/api/post-image/1614179891949336.jpg)

![1614179998615992.jpg](/api/post-image/1614179998615992.jpg)

![1614180021949323.jpg](/api/post-image/1614180021949323.jpg)',
   '2017-08-17 15:57:23', NULL, 1, 0, 0, '2017-08-17 15:57:23', u.Id, '2017-08-17 15:57:23', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #87  |  2017-08-18 18:41:52 UTC  |  2 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Got a visitor a couple minutes ago.', 255),
   LEFT(N'Got a visitor a couple minutes ago.  She is making herself at home at our front door.', 500),
   N'Got a visitor a couple minutes ago.  She is making herself at home at our front door.

![1615289681838357.jpg](/api/post-image/1615289681838357.jpg)

![1615289761838349.jpg](/api/post-image/1615289761838349.jpg)

*(1 video(s) from this post not yet imported)*',
   '2017-08-18 18:41:52', NULL, 1, 0, 0, '2017-08-18 18:41:52', u.Id, '2017-08-18 18:41:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #88  |  2017-09-18 15:48:13 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'John & Carl are in the blue bomber and headed back to ky to fetch Carol.', 255),
   LEFT(N'John & Carl are in the blue bomber and headed back to ky to fetch Carol.  They left at about 9:30 AM (Mountain Time).', 500),
   N'John & Carl are in the blue bomber and headed back to ky to fetch Carol.  They left at about 9:30 AM (Mountain Time).',
   '2017-09-18 15:48:13', NULL, 1, 0, 0, '2017-09-18 15:48:13', u.Id, '2017-09-18 15:48:13', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #90  |  2017-09-23 13:21:13 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Did someone say American Ninja warrior?', 255),
   LEFT(N'Did someone say American Ninja warrior?', 500),
   N'Did someone say American Ninja warrior?',
   '2017-09-23 13:21:13', NULL, 1, 0, 0, '2017-09-23 13:21:13', u.Id, '2017-09-23 13:21:13', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #91  |  2017-10-22 23:45:47 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Punched my Colorado otc tag on opening morning.', 255),
   LEFT(N'Punched my Colorado otc tag on opening morning.   Spent the next 14 hours getting him back to the truck.  I am thinking about getting a llama now.', 500),
   N'Punched my Colorado otc tag on opening morning.   Spent the next 14 hours getting him back to the truck.  I am thinking about getting a llama now.

![1674661549234503.jpg](/api/post-image/1674661549234503.jpg)

![1674661595901165.jpg](/api/post-image/1674661595901165.jpg)',
   '2017-10-22 23:45:47', NULL, 1, 0, 0, '2017-10-22 23:45:47', u.Id, '2017-10-22 23:45:47', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #92  |  2017-10-31 13:17:14 UTC  |  6 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Halloween!', 255),
   LEFT(N'Happy Halloween!  Took a little coaxing, but Sidney went elbow deep in the gross pumpkin guts.', 500),
   N'Happy Halloween!  Took a little coaxing, but Sidney went elbow deep in the gross pumpkin guts.

![1683182958382362.jpg](/api/post-image/1683182958382362.jpg)

![1683183045049020.jpg](/api/post-image/1683183045049020.jpg)

![1683183131715678.jpg](/api/post-image/1683183131715678.jpg)

![1683183201715671.jpg](/api/post-image/1683183201715671.jpg)

![1683183275048997.jpg](/api/post-image/1683183275048997.jpg)

![1683183331715658.jpg](/api/post-image/1683183331715658.jpg)',
   '2017-10-31 13:17:14', NULL, 1, 0, 0, '2017-10-31 13:17:14', u.Id, '2017-10-31 13:17:14', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #94  |  2017-12-10 19:09:51 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Best part of a ski day.', 255),
   LEFT(N'Best part of a ski day.  Marshmallow pizza.', 500),
   N'Best part of a ski day.  Marshmallow pizza.

![1724360640931260.jpg](/api/post-image/1724360640931260.jpg)',
   '2017-12-10 19:09:51', NULL, 1, 0, 0, '2017-12-10 19:09:51', u.Id, '2017-12-10 19:09:51', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #95  |  2017-12-20 02:20:05 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'check out this guy - from the camera on the back of our home.', 255),
   LEFT(N'check out this guy - from the camera on the back of our home.  He came around along with a passel of other nice looking bucks.', 500),
   N'check out this guy - from the camera on the back of our home.  He came around along with a passel of other nice looking bucks.',
   '2017-12-20 02:20:05', NULL, 1, 0, 0, '2017-12-20 02:20:05', u.Id, '2017-12-20 02:20:05', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #96  |  2017-12-29 21:36:07 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Santa joined the unicorn and I at Winter Park for a nice blue bird day.', 255),
   LEFT(N'Santa joined the unicorn and I at Winter Park for a nice blue bird day.', 500),
   N'Santa joined the unicorn and I at Winter Park for a nice blue bird day.

![1743437525690238.jpg](/api/post-image/1743437525690238.jpg)

![1743437585690232.jpg](/api/post-image/1743437585690232.jpg)

![1743437659023558.jpg](/api/post-image/1743437659023558.jpg)',
   '2017-12-29 21:36:07', NULL, 1, 0, 0, '2017-12-29 21:36:07', u.Id, '2017-12-29 21:36:07', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #97  |  2017-12-30 01:00:52 UTC  |  4 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'My little unicorn and I had a great blue bird day up at Winter Park.', 255),
   LEFT(N'My little unicorn and I had a great blue bird day up at Winter Park.  We even ran into Santa as he was enjoying his post Xmas holiday vacation.', 500),
   N'My little unicorn and I had a great blue bird day up at Winter Park.  We even ran into Santa as he was enjoying his post Xmas holiday vacation.

![1743572202343437.jpg](/api/post-image/1743572202343437.jpg)

![1743572269010097.jpg](/api/post-image/1743572269010097.jpg)

![1743572329010091.jpg](/api/post-image/1743572329010091.jpg)

![1743572372343420.jpg](/api/post-image/1743572372343420.jpg)

*(1 video(s) from this post not yet imported)*',
   '2017-12-30 01:00:52', NULL, 1, 0, 0, '2017-12-30 01:00:52', u.Id, '2017-12-30 01:00:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #98  |  2017-12-30 01:10:18 UTC  |  4 photo(s) linked, 2 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Dillion ice castle today.', 255),
   LEFT(N'Dillion ice castle today.  Great time - once we navigated past the world''s greatest pot hole that snarled up I70.  The ice slide was worth the wait.', 500),
   N'Dillion ice castle today.  Great time - once we navigated past the world''s greatest pot hole that snarled up I70.  The ice slide was worth the wait.

![1743578499009474.jpg](/api/post-image/1743578499009474.jpg)

![1743578589009465.jpg](/api/post-image/1743578589009465.jpg)

![1743578632342794.jpg](/api/post-image/1743578632342794.jpg)

![1743578732342784.jpg](/api/post-image/1743578732342784.jpg)

*(2 video(s) from this post not yet imported)*',
   '2017-12-30 01:10:18', NULL, 1, 0, 0, '2017-12-30 01:10:18', u.Id, '2017-12-30 01:10:18', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #99  |  2017-12-30 01:27:15 UTC  |  27 photo(s) linked, 3 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Thanksgiving vacation this year was a bit warmer than usual.', 255),
   LEFT(N'Thanksgiving vacation this year was a bit warmer than usual.', 500),
   N'Thanksgiving vacation this year was a bit warmer than usual.

![1743585692342088.jpg](/api/post-image/1743585692342088.jpg)

![1743585865675404.jpg](/api/post-image/1743585865675404.jpg)

![1743585942342063.jpg](/api/post-image/1743585942342063.jpg)

![1743586025675388.jpg](/api/post-image/1743586025675388.jpg)

![1743586125675378.jpg](/api/post-image/1743586125675378.jpg)

![1743586262342031.jpg](/api/post-image/1743586262342031.jpg)

![1743586342342023.jpg](/api/post-image/1743586342342023.jpg)

![1743586385675352.jpg](/api/post-image/1743586385675352.jpg)

![1743586592341998.jpg](/api/post-image/1743586592341998.jpg)

![1743586655675325.jpg](/api/post-image/1743586655675325.jpg)

![1743586695675321.jpg](/api/post-image/1743586695675321.jpg)

![1743586762341981.jpg](/api/post-image/1743586762341981.jpg)

![1743586809008643.jpg](/api/post-image/1743586809008643.jpg)

![1743586872341970.jpg](/api/post-image/1743586872341970.jpg)

![1743586965675294.jpg](/api/post-image/1743586965675294.jpg)

![1743587042341953.jpg](/api/post-image/1743587042341953.jpg)

![1743587172341940.jpg](/api/post-image/1743587172341940.jpg)

![1743587259008598.jpg](/api/post-image/1743587259008598.jpg)

![1743587325675258.jpg](/api/post-image/1743587325675258.jpg)

![1743587385675252.jpg](/api/post-image/1743587385675252.jpg)

![1743587919008532.jpg](/api/post-image/1743587919008532.jpg)

![1743587969008527.jpg](/api/post-image/1743587969008527.jpg)

![1743588059008518.jpg](/api/post-image/1743588059008518.jpg)

![1743588115675179.jpg](/api/post-image/1743588115675179.jpg)

![1743588182341839.jpg](/api/post-image/1743588182341839.jpg)

![1743588259008498.jpg](/api/post-image/1743588259008498.jpg)

![1743588299008494.jpg](/api/post-image/1743588299008494.jpg)

*(3 video(s) from this post not yet imported)*',
   '2017-12-30 01:27:15', NULL, 1, 0, 0, '2017-12-30 01:27:15', u.Id, '2017-12-30 01:27:15', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
