-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #1  |  2010-02-26 03:53:44 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We made it up to Copper Mountain last weekend.', 255),
   LEFT(N'We made it up to Copper Mountain last weekend. The snow was great, but we really could have lived without all the ski traffic.', 500),
   N'We made it up to Copper Mountain last weekend. The snow was great, but we really could have lived without all the ski traffic.',
   '2010-02-26 03:53:44', NULL, 1, 0, 0, '2010-02-26 03:53:44', u.Id, '2010-02-26 03:53:44', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #2  |  2010-02-26 04:22:47 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Updating my TripAdvisor Map.', 255),
   LEFT(N'Updating my TripAdvisor Map.  I wish I would have started this a few years back.', 500),
   N'Updating my TripAdvisor Map.  I wish I would have started this a few years back.',
   '2010-02-26 04:22:47', NULL, 1, 0, 0, '2010-02-26 04:22:47', u.Id, '2010-02-26 04:22:47', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #3  |  2010-03-14 18:27:20 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Finally figured out how to avoid ski traffic.', 255),
   LEFT(N'Finally figured out how to avoid ski traffic.  All you need to do is head up to Steamboat on Thursday night and drive back I70 on Friday night.', 500),
   N'Finally figured out how to avoid ski traffic.  All you need to do is head up to Steamboat on Thursday night and drive back I70 on Friday night.',
   '2010-03-14 18:27:20', NULL, 1, 0, 0, '2010-03-14 18:27:20', u.Id, '2010-03-14 18:27:20', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
