-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #213  |  2026-02-23 23:07:54 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'It''s been a minute.', 255),
   LEFT(N'It''s been a minute.  Happy Birthday, Mariusz! 👯🎉🥂', 500),
   N'It''s been a minute.  Happy Birthday, Mariusz! 👯🎉🥂',
   '2026-02-23 23:07:54', NULL, 1, 0, 0, '2026-02-23 23:07:54', u.Id, '2026-02-23 23:07:54', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #223  |  2026-03-20 17:12:50 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'''I Don’t Age.', 255),
   LEFT(N'''I Don’t Age. I Level Up'' ~ RIP @[100044120782094:2048:Chuck Norris]', 500),
   N'''I Don’t Age. I Level Up'' ~ RIP @[100044120782094:2048:Chuck Norris]',
   '2026-03-20 17:12:50', NULL, 1, 0, 0, '2026-03-20 17:12:50', u.Id, '2026-03-20 17:12:50', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
