-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #20  |  2014-02-04 17:00:24 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'shush...don''t tell anyone, we made a snowman.', 255),
   LEFT(N'shush...don''t tell anyone, we made a snowman.', 500),
   N'shush...don''t tell anyone, we made a snowman.

![701070603260274.jpg](/api/post-image/701070603260274.jpg)',
   '2014-02-04 17:00:24', NULL, 1, 0, 0, '2014-02-04 17:00:24', u.Id, '2014-02-04 17:00:24', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #21  |  2014-04-20 16:57:48 UTC  |  4 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Easter morning - before the sugar crash.', 255),
   LEFT(N'Easter morning - before the sugar crash.', 500),
   N'Easter morning - before the sugar crash.

![737776639589670.jpg](/api/post-image/737776639589670.jpg)

![737776856256315.jpg](/api/post-image/737776856256315.jpg)

![737777092922958.jpg](/api/post-image/737777092922958.jpg)

![737777119589622.jpg](/api/post-image/737777119589622.jpg)',
   '2014-04-20 16:57:48', NULL, 1, 0, 0, '2014-04-20 16:57:48', u.Id, '2014-04-20 16:57:48', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #22  |  2014-04-26 15:52:06 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s rendition of mister alligator and the monkeys.', 255),
   LEFT(N'Sidney''s rendition of mister alligator and the monkeys.', 500),
   N'Sidney''s rendition of mister alligator and the monkeys.

*(1 video(s) from this post not yet imported)*',
   '2014-04-26 15:52:06', NULL, 1, 0, 0, '2014-04-26 15:52:06', u.Id, '2014-04-26 15:52:06', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #23  |  2014-05-12 23:32:52 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Olaf''s big brother is back in town!', 255),
   LEFT(N'Olaf''s big brother is back in town!', 500),
   N'Olaf''s big brother is back in town!

![749995315034469.jpg](/api/post-image/749995315034469.jpg)',
   '2014-05-12 23:32:52', NULL, 1, 0, 0, '2014-05-12 23:32:52', u.Id, '2014-05-12 23:32:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #24  |  2014-05-19 02:18:43 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We hiked into rampart range reservoir today to stretch our legs and test our luck.', 255),
   LEFT(N'We hiked into rampart range reservoir today to stretch our legs and test our luck.  Sidney''s first time fishing with her new buzz light year fishing rod.   I''ll be asking her for fishing tips in a couple years..', 500),
   N'We hiked into rampart range reservoir today to stretch our legs and test our luck.  Sidney''s first time fishing with her new buzz light year fishing rod.   I''ll be asking her for fishing tips in a couple years..

*(1 video(s) from this post not yet imported)*',
   '2014-05-19 02:18:43', NULL, 1, 0, 0, '2014-05-19 02:18:43', u.Id, '2014-05-19 02:18:43', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #25  |  2014-07-11 13:27:04 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Hopefully this makes my weekend just a bit easier:)', 255),
   LEFT(N'Hopefully this makes my weekend just a bit easier:)', 500),
   N'Hopefully this makes my weekend just a bit easier:)',
   '2014-07-11 13:27:04', NULL, 1, 0, 0, '2014-07-11 13:27:04', u.Id, '2014-07-11 13:27:04', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #26  |  2014-07-15 03:15:41 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney convinced me to hop on a pachyderm with her and take it for a spin at the renaissance festival.', 255),
   LEFT(N'Sidney convinced me to hop on a pachyderm with her and take it for a spin at the renaissance festival.', 500),
   N'Sidney convinced me to hop on a pachyderm with her and take it for a spin at the renaissance festival.

![783909641643036.jpg](/api/post-image/783909641643036.jpg)

![783909674976366.jpg](/api/post-image/783909674976366.jpg)',
   '2014-07-15 03:15:41', NULL, 1, 0, 0, '2014-07-15 03:15:41', u.Id, '2014-07-15 03:15:41', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #27  |  2014-07-28 03:23:10 UTC  |  8 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Guess who is 36" tall', 255),
   LEFT(N'Guess who is 36" tall', 500),
   N'Guess who is 36" tall

![790274167673250.jpg](/api/post-image/790274167673250.jpg)

![790274181006582.jpg](/api/post-image/790274181006582.jpg)

![790274211006579.jpg](/api/post-image/790274211006579.jpg)

![790274231006577.jpg](/api/post-image/790274231006577.jpg)

![790274251006575.jpg](/api/post-image/790274251006575.jpg)

![790274287673238.jpg](/api/post-image/790274287673238.jpg)

![790274327673234.jpg](/api/post-image/790274327673234.jpg)

![790274421006558.jpg](/api/post-image/790274421006558.jpg)',
   '2014-07-28 03:23:10', NULL, 1, 0, 0, '2014-07-28 03:23:10', u.Id, '2014-07-28 03:23:10', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #28  |  2014-07-30 00:35:02 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Aunt Shannon - Sidney really likes the ring pops!', 255),
   LEFT(N'Aunt Shannon - Sidney really likes the ring pops!  You can tell from the pumpkin in the pic (taken today)-we try to keep her ring pop habit under control.', 500),
   N'Aunt Shannon - Sidney really likes the ring pops!  You can tell from the pumpkin in the pic (taken today)-we try to keep her ring pop habit under control.

![791252230908777.jpg](/api/post-image/791252230908777.jpg)',
   '2014-07-30 00:35:02', NULL, 1, 0, 0, '2014-07-30 00:35:02', u.Id, '2014-07-30 00:35:02', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #29  |  2014-08-02 23:15:42 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Just used smile.amazon.com and it felt good!', 255),
   LEFT(N'Just used smile.amazon.com and it felt good!', 500),
   N'Just used smile.amazon.com and it felt good!',
   '2014-08-02 23:15:42', NULL, 1, 0, 0, '2014-08-02 23:15:42', u.Id, '2014-08-02 23:15:42', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #30  |  2014-08-10 02:30:12 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Scratch that off the bucket list.', 255),
   LEFT(N'Scratch that off the bucket list. Finally managed to knock over the lead milk bottles at the fair to win a jumbo stuffed animal.    #goodday', 500),
   N'Scratch that off the bucket list. Finally managed to knock over the lead milk bottles at the fair to win a jumbo stuffed animal.    #goodday

![796820727018594.jpg](/api/post-image/796820727018594.jpg)',
   '2014-08-10 02:30:12', NULL, 1, 0, 0, '2014-08-10 02:30:12', u.Id, '2014-08-10 02:30:12', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #31  |  2014-09-21 03:30:36 UTC  |  5 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s day out with Thomas the train at the Colorado Railroad Museum in Golden.', 255),
   LEFT(N'Sidney''s day out with Thomas the train at the Colorado Railroad Museum in Golden.  I think she liked it more than last xmas.', 500),
   N'Sidney''s day out with Thomas the train at the Colorado Railroad Museum in Golden.  I think she liked it more than last xmas.

![817429621624371.jpg](/api/post-image/817429621624371.jpg)

![817429638291036.jpg](/api/post-image/817429638291036.jpg)

![817429654957701.jpg](/api/post-image/817429654957701.jpg)

![817429681624365.jpg](/api/post-image/817429681624365.jpg)

![817429744957692.jpg](/api/post-image/817429744957692.jpg)',
   '2014-09-21 03:30:36', NULL, 1, 0, 0, '2014-09-21 03:30:36', u.Id, '2014-09-21 03:30:36', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #32  |  2014-10-21 01:18:23 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Thanks for providing us with hours of entertainment (without all the smells) Aunt Shannon.', 255),
   LEFT(N'Thanks for providing us with hours of entertainment (without all the smells) Aunt Shannon.', 500),
   N'Thanks for providing us with hours of entertainment (without all the smells) Aunt Shannon.

*(1 video(s) from this post not yet imported)*',
   '2014-10-21 01:18:23', NULL, 1, 0, 0, '2014-10-21 01:18:23', u.Id, '2014-10-21 01:18:23', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #33  |  2014-10-31 01:18:28 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Jeri Hazeltine fixed Sidney Hazeltine up with braided pigtails this morning.', 255),
   LEFT(N'Jeri Hazeltine fixed Sidney Hazeltine up with braided pigtails this morning.  I had to share.', 500),
   N'Jeri Hazeltine fixed Sidney Hazeltine up with braided pigtails this morning.  I had to share.

![839041522796514.jpg](/api/post-image/839041522796514.jpg)',
   '2014-10-31 01:18:28', NULL, 1, 0, 0, '2014-10-31 01:18:28', u.Id, '2014-10-31 01:18:28', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #34  |  2014-11-01 01:47:31 UTC  |  13 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Halloween', 255),
   LEFT(N'Happy Halloween', 500),
   N'Happy Halloween

![839582352742431.jpg](/api/post-image/839582352742431.jpg)

![839582426075757.jpg](/api/post-image/839582426075757.jpg)

![839582472742419.jpg](/api/post-image/839582472742419.jpg)

![839582526075747.jpg](/api/post-image/839582526075747.jpg)

![839582572742409.jpg](/api/post-image/839582572742409.jpg)

![839582599409073.jpg](/api/post-image/839582599409073.jpg)

![839582636075736.jpg](/api/post-image/839582636075736.jpg)

![839582672742399.jpg](/api/post-image/839582672742399.jpg)

![839582702742396.jpg](/api/post-image/839582702742396.jpg)

![839582746075725.jpg](/api/post-image/839582746075725.jpg)

![839582879409045.jpg](/api/post-image/839582879409045.jpg)

![839582919409041.jpg](/api/post-image/839582919409041.jpg)

![839582956075704.jpg](/api/post-image/839582956075704.jpg)',
   '2014-11-01 01:47:31', NULL, 1, 0, 0, '2014-11-01 01:47:31', u.Id, '2014-11-01 01:47:31', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #36  |  2014-12-06 18:27:27 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'When you think of vacation, what comes to mind?.', 255),
   LEFT(N'When you think of vacation, what comes to mind?.', 500),
   N'When you think of vacation, what comes to mind?.

*(1 video(s) from this post not yet imported)*',
   '2014-12-06 18:27:27', NULL, 1, 0, 0, '2014-12-06 18:27:27', u.Id, '2014-12-06 18:27:27', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
