-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #155  |  2023-11-27 03:18:03 UTC  |  3 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Scouted the perfect tree.', 255),
   LEFT(N'Scouted the perfect tree.  Came back on opening day, tag in hand.  Bagged the perfect tree; sir chubbington.  Tis the season.', 500),
   N'Scouted the perfect tree.  Came back on opening day, tag in hand.  Bagged the perfect tree; sir chubbington.  Tis the season.

![7190358667664736.jpg](/api/post-image/7190358667664736.jpg)

![7190358784331391.jpg](/api/post-image/7190358784331391.jpg)

![7190358877664715.jpg](/api/post-image/7190358877664715.jpg)',
   '2023-11-27 03:18:03', NULL, 1, 0, 0, '2023-11-27 03:18:03', u.Id, '2023-11-27 03:18:03', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #156  |  2023-12-16 04:35:29 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Watching one of the better Xmas movies tonight.', 255),
   LEFT(N'Watching one of the better Xmas movies tonight.  Sidney Hazeltine has the clicker counting swear words.  She is currently at 58.  Yippee ki ya!!!  Merry Xmas!', 500),
   N'Watching one of the better Xmas movies tonight.  Sidney Hazeltine has the clicker counting swear words.  She is currently at 58.  Yippee ki ya!!!  Merry Xmas!

![7262391137128155.jpg](/api/post-image/7262391137128155.jpg)',
   '2023-12-16 04:35:29', NULL, 1, 0, 0, '2023-12-16 04:35:29', u.Id, '2023-12-16 04:35:29', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
