-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #101  |  2018-01-03 04:11:11 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'This is really good motivation to set a resolution.', 255),
   LEFT(N'This is really good motivation to set a resolution.', 500),
   N'This is really good motivation to set a resolution.',
   '2018-01-03 04:11:11', NULL, 1, 0, 0, '2018-01-03 04:11:11', u.Id, '2018-01-03 04:11:11', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #102  |  2018-01-07 04:02:44 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Evergreen lake today on skates.', 255),
   LEFT(N'Evergreen lake today on skates.', 500),
   N'Evergreen lake today on skates.

![1752646264769364.jpg](/api/post-image/1752646264769364.jpg)',
   '2018-01-07 04:02:44', NULL, 1, 0, 0, '2018-01-07 04:02:44', u.Id, '2018-01-07 04:02:44', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #104  |  2018-02-12 01:01:18 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'The apple doesn''t fall far from the tree.', 255),
   LEFT(N'The apple doesn''t fall far from the tree.  Sid stuck the landing on her third try.   Mad props!', 500),
   N'The apple doesn''t fall far from the tree.  Sid stuck the landing on her third try.   Mad props!

*(1 video(s) from this post not yet imported)*',
   '2018-02-12 01:01:18', NULL, 1, 0, 0, '2018-02-12 01:01:18', u.Id, '2018-02-12 01:01:18', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #105  |  2018-02-12 01:03:07 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Snow angels', 255),
   LEFT(N'Snow angels', 500),
   N'Snow angels

![1791929220841068.jpg](/api/post-image/1791929220841068.jpg)',
   '2018-02-12 01:03:07', NULL, 1, 0, 0, '2018-02-12 01:03:07', u.Id, '2018-02-12 01:03:07', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #106  |  2018-03-11 02:28:09 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney  and her ski group stopped in to check out one of the huts hidden up on Winter Park.', 255),
   LEFT(N'Sidney  and her ski group stopped in to check out one of the huts hidden up on Winter Park.  She is the one sporting the unicorn 🦄  helmet. Did you know they have around 40 huts on the ski resort?  I have skied there on and off the past ten years and this is the first I heard about them.   Pretty cool.', 500),
   N'Sidney  and her ski group stopped in to check out one of the huts hidden up on Winter Park.  She is the one sporting the unicorn 🦄  helmet. Did you know they have around 40 huts on the ski resort?  I have skied there on and off the past ten years and this is the first I heard about them.   Pretty cool.

![1822666797767310.jpg](/api/post-image/1822666797767310.jpg)',
   '2018-03-11 02:28:09', NULL, 1, 0, 0, '2018-03-11 02:28:09', u.Id, '2018-03-11 02:28:09', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #107  |  2018-03-18 15:17:24 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney faced a big fear on st.', 255),
   LEFT(N'Sidney faced a big fear on st. Patrick''s day - not a big bear like in the pic.  Her ski group ventured over to the bumps at Mary Jane.  Now she can proudly announce No Pain, No Jane!', 500),
   N'Sidney faced a big fear on st. Patrick''s day - not a big bear like in the pic.  Her ski group ventured over to the bumps at Mary Jane.  Now she can proudly announce No Pain, No Jane!

![1831517486882241.jpg](/api/post-image/1831517486882241.jpg)',
   '2018-03-18 15:17:24', NULL, 1, 0, 0, '2018-03-18 15:17:24', u.Id, '2018-03-18 15:17:24', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #108  |  2018-04-01 23:54:20 UTC  |  1 photo(s) linked, 2 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Easter at copper mountain.', 255),
   LEFT(N'Easter at copper mountain.  Sidney secured enough eggs to keep her sugar rush going all year.  Her technique is unmatched.  Watch the video is you doubt me.', 500),
   N'Easter at copper mountain.  Sidney secured enough eggs to keep her sugar rush going all year.  Her technique is unmatched.  Watch the video is you doubt me.

![1847509498616373.jpg](/api/post-image/1847509498616373.jpg)

*(2 video(s) from this post not yet imported)*',
   '2018-04-01 23:54:20', NULL, 1, 0, 0, '2018-04-01 23:54:20', u.Id, '2018-04-01 23:54:20', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #109  |  2018-04-27 18:23:30 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'And this is why I don''t friend coworkers.', 255),
   LEFT(N'And this is why I don''t friend coworkers.  Playing hooky on a Friday at Mary Jane with my ski buddy Sidney.', 500),
   N'And this is why I don''t friend coworkers.  Playing hooky on a Friday at Mary Jane with my ski buddy Sidney.

![1874405275926795.jpg](/api/post-image/1874405275926795.jpg)

![1874405399260116.jpg](/api/post-image/1874405399260116.jpg)',
   '2018-04-27 18:23:30', NULL, 1, 0, 0, '2018-04-27 18:23:30', u.Id, '2018-04-27 18:23:30', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #110  |  2018-05-11 19:48:41 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Stiff competition for fishing spots today at the lake.', 255),
   LEFT(N'Stiff competition for fishing spots today at the lake.', 500),
   N'Stiff competition for fishing spots today at the lake.

![1888864421147547.jpg](/api/post-image/1888864421147547.jpg)',
   '2018-05-11 19:48:41', NULL, 1, 0, 0, '2018-05-11 19:48:41', u.Id, '2018-05-11 19:48:41', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #111  |  2018-05-19 23:29:40 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Congratulations on one more trip around the sun.', 255),
   LEFT(N'Congratulations on one more trip around the sun.   Happy birthday!', 500),
   N'Congratulations on one more trip around the sun.   Happy birthday!',
   '2018-05-19 23:29:40', NULL, 1, 0, 0, '2018-05-19 23:29:40', u.Id, '2018-05-19 23:29:40', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #112  |  2018-06-05 02:34:25 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'It''s that time of year again.', 255),
   LEFT(N'It''s that time of year again.', 500),
   N'It''s that time of year again.

*(1 video(s) from this post not yet imported)*',
   '2018-06-05 02:34:25', NULL, 1, 0, 0, '2018-06-05 02:34:25', u.Id, '2018-06-05 02:34:25', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #113  |  2018-07-19 13:04:26 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'This is next level :)', 255),
   LEFT(N'This is next level :)', 500),
   N'This is next level :)',
   '2018-07-19 13:04:26', NULL, 1, 0, 0, '2018-07-19 13:04:26', u.Id, '2018-07-19 13:04:26', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #114  |  2018-07-25 00:49:22 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'I expected to see your name in the article when I clicked on it.', 255),
   LEFT(N'I expected to see your name in the article when I clicked on it.  Perhaps this could be your next adventure.', 500),
   N'I expected to see your name in the article when I clicked on it.  Perhaps this could be your next adventure.',
   '2018-07-25 00:49:22', NULL, 1, 0, 0, '2018-07-25 00:49:22', u.Id, '2018-07-25 00:49:22', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #115  |  2018-08-05 02:17:42 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Today,  we ride...and sometimes we crash.', 255),
   LEFT(N'Today,  we ride...and sometimes we crash.   But today,  we ride...and...!', 500),
   N'Today,  we ride...and sometimes we crash.   But today,  we ride...and...!

*(1 video(s) from this post not yet imported)*',
   '2018-08-05 02:17:42', NULL, 1, 0, 0, '2018-08-05 02:17:42', u.Id, '2018-08-05 02:17:42', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #116  |  2018-08-05 02:22:48 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Can you say ninja...Lana...', 255),
   LEFT(N'Can you say ninja...Lana...', 500),
   N'Can you say ninja...Lana...

*(1 video(s) from this post not yet imported)*',
   '2018-08-05 02:22:48', NULL, 1, 0, 0, '2018-08-05 02:22:48', u.Id, '2018-08-05 02:22:48', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #117  |  2018-08-16 15:32:37 UTC  |  5 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney headed into Bergen for her first day of Second Grade this morning.', 255),
   LEFT(N'Sidney headed into Bergen for her first day of Second Grade this morning.  We managed to step up the pig tails from last year. Thanks again Jeri for showing me some new hair tricks.', 500),
   N'Sidney headed into Bergen for her first day of Second Grade this morning.  We managed to step up the pig tails from last year. Thanks again Jeri for showing me some new hair tricks.

![2028931567140831.jpg](/api/post-image/2028931567140831.jpg)

![2028931490474172.jpg](/api/post-image/2028931490474172.jpg)

![2028931457140842.jpg](/api/post-image/2028931457140842.jpg)

![2028931957140792.jpg](/api/post-image/2028931957140792.jpg)

![2029516960415625.jpg](/api/post-image/2029516960415625.jpg)',
   '2018-08-16 15:32:37', NULL, 1, 0, 0, '2018-08-16 15:32:37', u.Id, '2018-08-16 15:32:37', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #118  |  2018-09-09 22:24:11 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Tis the season.', 255),
   LEFT(N'Tis the season.', 500),
   N'Tis the season.

*(1 video(s) from this post not yet imported)*',
   '2018-09-09 22:24:11', NULL, 1, 0, 0, '2018-09-09 22:24:11', u.Id, '2018-09-09 22:24:11', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #119  |  2018-09-24 00:26:56 UTC  |  4 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Great bike ride today.', 255),
   LEFT(N'Great bike ride today.  We did the full 12 miles of the mineral belt loop in Leadville.  Only found one big foot along the way.', 500),
   N'Great bike ride today.  We did the full 12 miles of the mineral belt loop in Leadville.  Only found one big foot along the way.

![2082391395128181.jpg](/api/post-image/2082391395128181.jpg)

![2082391465128174.jpg](/api/post-image/2082391465128174.jpg)

![2082391538461500.jpg](/api/post-image/2082391538461500.jpg)

![2082391621794825.jpg](/api/post-image/2082391621794825.jpg)',
   '2018-09-24 00:26:56', NULL, 1, 0, 0, '2018-09-24 00:26:56', u.Id, '2018-09-24 00:26:56', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #120  |  2018-10-07 21:50:13 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney added her own cairn to help the troll stay on course.', 255),
   LEFT(N'Sidney added her own cairn to help the troll stay on course.', 500),
   N'Sidney added her own cairn to help the troll stay on course.

![2100177226682931.jpg](/api/post-image/2100177226682931.jpg)',
   '2018-10-07 21:50:13', NULL, 1, 0, 0, '2018-10-07 21:50:13', u.Id, '2018-10-07 21:50:13', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #121  |  2018-10-20 01:41:59 UTC  |  19 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Another elk hunt in the books.', 255),
   LEFT(N'Another elk hunt in the books.  A great season with lots of twists and turns.  We got our tire chains muddy, broke in our cold weather gear, and managed to meet a couple very nice and extremely helpful cowboys.', 500),
   N'Another elk hunt in the books.  A great season with lots of twists and turns.  We got our tire chains muddy, broke in our cold weather gear, and managed to meet a couple very nice and extremely helpful cowboys.

![2116524408381546.jpg](/api/post-image/2116524408381546.jpg)

![2116524535048200.jpg](/api/post-image/2116524535048200.jpg)

![2116524755048178.jpg](/api/post-image/2116524755048178.jpg)

![2116524865048167.jpg](/api/post-image/2116524865048167.jpg)

![2116524971714823.jpg](/api/post-image/2116524971714823.jpg)

![2116525088381478.jpg](/api/post-image/2116525088381478.jpg)

![2116525365048117.jpg](/api/post-image/2116525365048117.jpg)

![2116531378380849.jpg](/api/post-image/2116531378380849.jpg)

![2116539845046669.jpg](/api/post-image/2116539845046669.jpg)

![2116570558376931.jpg](/api/post-image/2116570558376931.jpg)

![2116570918376895.jpg](/api/post-image/2116570918376895.jpg)

![2116571061710214.jpg](/api/post-image/2116571061710214.jpg)

![2116571245043529.jpg](/api/post-image/2116571245043529.jpg)

![2116571401710180.jpg](/api/post-image/2116571401710180.jpg)

![2116571605043493.jpg](/api/post-image/2116571605043493.jpg)

![2116571781710142.jpg](/api/post-image/2116571781710142.jpg)

![2116573758376611.jpg](/api/post-image/2116573758376611.jpg)

![2116574008376586.jpg](/api/post-image/2116574008376586.jpg)

![2116583921708928.jpg](/api/post-image/2116583921708928.jpg)',
   '2018-10-20 01:41:59', NULL, 1, 0, 0, '2018-10-20 01:41:59', u.Id, '2018-10-20 01:41:59', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #122  |  2018-10-25 15:37:32 UTC  |  0 photo(s) linked, 2 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We captured our first Linx on the security system last night.', 255),
   LEFT(N'We captured our first Linx on the security system last night.', 500),
   N'We captured our first Linx on the security system last night.

*(2 video(s) from this post not yet imported)*',
   '2018-10-25 15:37:32', NULL, 1, 0, 0, '2018-10-25 15:37:32', u.Id, '2018-10-25 15:37:32', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #123  |  2018-10-27 23:23:10 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'A night at the museum was a blast.', 255),
   LEFT(N'A night at the museum was a blast.  Our egg survived the zip line and should go on to live a long and full life.', 500),
   N'A night at the museum was a blast.  Our egg survived the zip line and should go on to live a long and full life.',
   '2018-10-27 23:23:10', NULL, 1, 0, 0, '2018-10-27 23:23:10', u.Id, '2018-10-27 23:23:10', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #125  |  2018-11-11 20:31:52 UTC  |  2 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Sidney''s first snow creature of the season.', 255),
   LEFT(N'Sidney''s first snow creature of the season. Looking forward to snow scream with dinner tonight.', 500),
   N'Sidney''s first snow creature of the season. Looking forward to snow scream with dinner tonight.

![2151849051515748.jpg](/api/post-image/2151849051515748.jpg)

![2151849251515728.jpg](/api/post-image/2151849251515728.jpg)',
   '2018-11-11 20:31:52', NULL, 1, 0, 0, '2018-11-11 20:31:52', u.Id, '2018-11-11 20:31:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #126  |  2018-11-12 23:25:39 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'gotta love our little mountain town.', 255),
   LEFT(N'gotta love our little mountain town.', 500),
   N'gotta love our little mountain town.',
   '2018-11-12 23:25:39', NULL, 1, 0, 0, '2018-11-12 23:25:39', u.Id, '2018-11-12 23:25:39', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #127  |  2018-11-23 02:50:35 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'The tooth fairy drives a monster truck and Sidney loves monster trucks.', 255),
   LEFT(N'The tooth fairy drives a monster truck and Sidney loves monster trucks.  Check out how SHE chose to extract her tooth. Anyone have a loose tooth they would like her to deal with?', 500),
   N'The tooth fairy drives a monster truck and Sidney loves monster trucks.  Check out how SHE chose to extract her tooth. Anyone have a loose tooth they would like her to deal with?

*(1 video(s) from this post not yet imported)*',
   '2018-11-23 02:50:35', NULL, 1, 0, 0, '2018-11-23 02:50:35', u.Id, '2018-11-23 02:50:35', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #128  |  2018-11-27 19:39:34 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Looks like the mule deer rut is still going strong.', 255),
   LEFT(N'Looks like the mule deer rut is still going strong.', 500),
   N'Looks like the mule deer rut is still going strong.

*(1 video(s) from this post not yet imported)*',
   '2018-11-27 19:39:34', NULL, 1, 0, 0, '2018-11-27 19:39:34', u.Id, '2018-11-27 19:39:34', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
