-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #144  |  2022-02-09 01:07:06 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'If anyone else finds themselves searching for wordle hints, I created a simple little helper.', 255),
   LEFT(N'If anyone else finds themselves searching for wordle hints, I created a simple little helper.   https://tjhazel.github.io/wordlehints/', 500),
   N'If anyone else finds themselves searching for wordle hints, I created a simple little helper.   https://tjhazel.github.io/wordlehints/',
   '2022-02-09 01:07:06', NULL, 1, 0, 0, '2022-02-09 01:07:06', u.Id, '2022-02-09 01:07:06', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #145  |  2022-03-06 00:43:47 UTC  |  1 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Elk tenderloin, wine mushroom reduction, with a parmesan crusted asparagus and Jeri''s homemade key lime pie. Mummmmmmmm.', 255),
   LEFT(N'Elk tenderloin, wine mushroom reduction, with a parmesan crusted asparagus and Jeri''s homemade key lime pie. Mummmmmmmm.', 500),
   N'Elk tenderloin, wine mushroom reduction, with a parmesan crusted asparagus and Jeri''s homemade key lime pie. Mummmmmmmm.

![5202884876412135.jpg](/api/post-image/5202884876412135.jpg)',
   '2022-03-06 00:43:47', NULL, 1, 0, 0, '2022-03-06 00:43:47', u.Id, '2022-03-06 00:43:47', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #148  |  2022-03-24 23:21:11 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We were walking around the Evergreen lake in the first week of the new year discussing what we would like to do this year.  Sidney, who has been hitting the French lessons on Duolingo for 300+ days said she wanted to go to eat a baguette in France and...', 255),
   LEFT(N'We were walking around the Evergreen lake in the first week of the new year discussing what we would like to do this year.  Sidney, who has been hitting the French lessons on Duolingo for 300+ days said she wanted to go to eat a baguette in France and visit the Eiffel Tower.  Whelp, apparently Jeri and I are easily influenced and highly vacation starved.  Paris - what a wonderful trip and a ton of great experiences for the whole family.', 500),
   N'We were walking around the Evergreen lake in the first week of the new year discussing what we would like to do this year.  Sidney, who has been hitting the French lessons on Duolingo for 300+ days said she wanted to go to eat a baguette in France and visit the Eiffel Tower.  Whelp, apparently Jeri and I are easily influenced and highly vacation starved.  Paris - what a wonderful trip and a ton of great experiences for the whole family.',
   '2022-03-24 23:21:11', NULL, 1, 0, 0, '2022-03-24 23:21:11', u.Id, '2022-03-24 23:21:11', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #151  |  2022-10-19 23:33:52 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'2022 Elk Season is over.', 255),
   LEFT(N'2022 Elk Season is over.  Was a great drop camp, more than 20 years in the making.', 500),
   N'2022 Elk Season is over.  Was a great drop camp, more than 20 years in the making.',
   '2022-10-19 23:33:52', NULL, 1, 0, 0, '2022-10-19 23:33:52', u.Id, '2022-10-19 23:33:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #152  |  2022-10-31 13:22:52 UTC  |  9 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'A lively baguette escaped the Hazeltine Boulangerie.', 255),
   LEFT(N'A lively baguette escaped the Hazeltine Boulangerie.  Happy Halloween!', 500),
   N'A lively baguette escaped the Hazeltine Boulangerie.  Happy Halloween!

![5876797149020901.jpg](/api/post-image/5876797149020901.jpg)

![5876797469020869.jpg](/api/post-image/5876797469020869.jpg)

![5876797242354225.jpg](/api/post-image/5876797242354225.jpg)

![5876796169020999.jpg](/api/post-image/5876796169020999.jpg)

![5876796159021000.jpg](/api/post-image/5876796159021000.jpg)

![5876797039020912.jpg](/api/post-image/5876797039020912.jpg)

![5876797419020874.jpg](/api/post-image/5876797419020874.jpg)

![5876795625687720.jpg](/api/post-image/5876795625687720.jpg)

![5876795175687765.jpg](/api/post-image/5876795175687765.jpg)',
   '2022-10-31 13:22:52', NULL, 1, 0, 0, '2022-10-31 13:22:52', u.Id, '2022-10-31 13:22:52', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
