-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #192  |  2025-07-25 16:26:06 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'I think someone sent your cliff dive to AFV 😂', 255),
   LEFT(N'I think someone sent your cliff dive to AFV 😂', 500),
   N'I think someone sent your cliff dive to AFV 😂',
   '2025-07-25 16:26:06', NULL, 1, 0, 0, '2025-07-25 16:26:06', u.Id, '2025-07-25 16:26:06', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #195  |  2025-08-14 14:20:14 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Happy Birthday, Jon!', 255),
   LEFT(N'Happy Birthday, Jon! 👯🎂🌟  We were thinking about you last night while watching The Pitt (https://www.facebook.com/profile.php?id=61574673673652).  I have a whole new respect for what you do.  Have a great day!', 500),
   N'Happy Birthday, Jon! 👯🎂🌟  We were thinking about you last night while watching The Pitt (https://www.facebook.com/profile.php?id=61574673673652).  I have a whole new respect for what you do.  Have a great day!',
   '2025-08-14 14:20:14', NULL, 1, 0, 0, '2025-08-14 14:20:14', u.Id, '2025-08-14 14:20:14', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
