-- Auto-generated by Tools/facebook_import/generate_posts_sql.py -- DO NOT hand-edit, regenerate instead.
-- Review before running. Each post is its own batch (GO) so a failure doesn't roll back everything before it.
-- Images are plain files in Albums/PostImages/, served via /api/post-image/{fileName}. Nothing binary in this script.

-- Post #136  |  2020-05-19 15:58:23 UTC  |  0 photo(s) linked, 1 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'We wanted to reach out and say Happy Birthday!', 255),
   LEFT(N'We wanted to reach out and say Happy Birthday!  Sure hope you have a great day and a wonderful year ahead!', 500),
   N'We wanted to reach out and say Happy Birthday!  Sure hope you have a great day and a wonderful year ahead!

*(1 video(s) from this post not yet imported)*',
   '2020-05-19 15:58:23', NULL, 1, 0, 0, '2020-05-19 15:58:23', u.Id, '2020-05-19 15:58:23', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #137  |  2020-07-31 00:47:50 UTC  |  0 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'Please copy and paste this to your status if you''re constantly being asked to copy and paste things to your status by people who copy and paste things to their statuses. Many people won''t copy and paste this, but my truly sarcastic friends (who are my...', 255),
   LEFT(N'Please copy and paste this to your status if you''re constantly being asked to copy and paste things to your status by people who copy and paste things to their statuses. Many people won''t copy and paste this, but my truly sarcastic friends (who are my favorites) will copy and paste it because they''re sarcastic by nature. If you don''t copy and paste it, then this means you hate bacon. And if you hate bacon, the government wins, and a unicorn dies. Possibly puppies as well. And occasionally baby g', 500),
   N'Please copy and paste this to your status if you''re constantly being asked to copy and paste things to your status by people who copy and paste things to their statuses. Many people won''t copy and paste this, but my truly sarcastic friends (who are my favorites) will copy and paste it because they''re sarcastic by nature. If you don''t copy and paste it, then this means you hate bacon. And if you hate bacon, the government wins, and a unicorn dies. Possibly puppies as well. And occasionally baby goats. But never dragons because of something to do with tomatoes.',
   '2020-07-31 00:47:50', NULL, 1, 0, 0, '2020-07-31 00:47:50', u.Id, '2020-07-31 00:47:50', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO

-- Post #138  |  2020-10-28 23:58:11 UTC  |  4 photo(s) linked, 0 video(s) skipped
DECLARE @NewPostIdTbl TABLE (PostId INT);
DECLARE @NewPostId INT;
INSERT INTO Posts (Title, PreviewText, Body, ReleaseDate, ExpireDate, CommentsEnabled, Approved, ViewCount, CreatedDate, CreatedByFk, ModifiedDate, ModifiedByFk)
OUTPUT INSERTED.PostId INTO @NewPostIdTbl
SELECT
   LEFT(N'2020 elk season is in the books.', 255),
   LEFT(N'2020 elk season is in the books.  Got in a few miles, had fun keeping up with Cody over the weekend, and some fun artic weather to camp in.  Thanks for the great prepped hot meals Jeri.', 500),
   N'2020 elk season is in the books.  Got in a few miles, had fun keeping up with Cody over the weekend, and some fun artic weather to camp in.  Thanks for the great prepped hot meals Jeri.

![3693329160701055.jpg](/api/post-image/3693329160701055.jpg)

![3693329670701004.jpg](/api/post-image/3693329670701004.jpg)

![3693330134034291.jpg](/api/post-image/3693330134034291.jpg)

![3693330537367584.jpg](/api/post-image/3693330537367584.jpg)',
   '2020-10-28 23:58:11', NULL, 1, 0, 0, '2020-10-28 23:58:11', u.Id, '2020-10-28 23:58:11', u.Id
FROM Users u WHERE u.Email = N'jhazeltine1@gmail.com';
SELECT @NewPostId = PostId FROM @NewPostIdTbl;
IF @NewPostId IS NOT NULL
BEGIN
   INSERT INTO PostCategories (PostFk, CategoryFk) VALUES (@NewPostId, 8);
END
GO
