// Standard 5-letter Wordle word list (uppercase)
export const WORDLE_WORDS: string[] = [
  // A
  "ABACK", "ABASE", "ABASH", "ABATE", "ABBEY", "ABBOT", "ABHOR", "ABIDE",
  "ABLER", "ABODE", "ABORT", "ABUSE", "ABYSS", "ACORN", "ACRID", "ACUTE",
  "ADAGE", "ADAPT", "ADEPT", "ADMIT", "ADOBE", "ADOPT", "ADORE", "ADULT",
  "AFTER", "AGILE", "AGING", "AGLOW", "AGONY", "AGREE", "AHEAD", "AIDER",
  "AISLE", "ALARM", "ALBUM", "ALDER", "ALGAE", "ALIAS", "ALIKE", "ALIGN",
  "ALIVE", "ALLAY", "ALLEY", "ALLOT", "ALLOW", "ALLOY", "ALOFT", "ALONE",
  "ALONG", "ALOOF", "ALOUD", "ALTAR", "ALTER", "AMAZE", "AMBLE", "AMEND",
  "AMISS", "AMUSE", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANNEX", "ANNOY",
  "ANTIC", "ANVIL", "AORTA", "APART", "APPLE", "APPLY", "APRON", "ARDOR",
  "ARENA", "ARISE", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW", "ARTSY",
  "ASCOT", "ASIDE", "ASPEN", "ATONE", "ATTIC", "AUDIO", "AUDIT", "AUGUR",
  "AVAIL", "AVOID", "AWAKE", "AWARE", "AWFUL", "AWOKE",

  // B
  "BADGE", "BADLY", "BAGEL", "BASIN", "BASIS", "BATCH", "BATHE", "BAYOU",
  "BEACH", "BEADY", "BEGAN", "BEGIN", "BEIGE", "BELOW", "BENCH", "BERRY",
  "BIBLE", "BIRCH", "BIRTH", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK",
  "BLAST", "BLAZE", "BLEAK", "BLEAT", "BLEED", "BLEND", "BLESS", "BLIND",
  "BLISS", "BLIMP", "BLINK", "BLOCK", "BLOOD", "BLOOM", "BLOWN", "BLUFF",
  "BLUNT", "BLURB", "BLURT", "BLUSH", "BOARD", "BOAST", "BOOZE", "BOTCH",
  "BOUND", "BOXER", "BRAID", "BRAKE", "BRAND", "BRAVE", "BRAWN", "BREAD",
  "BREAK", "BREED", "BRICK", "BRIDE", "BRIEF", "BRINE", "BRING", "BROAD",
  "BROKE", "BROOK", "BROOD", "BROWN", "BRUNT", "BRUTE", "BUDGE", "BULGE",
  "BUNCH", "BURNT", "BURST", "BUYER",

  // C
  "CABIN", "CAMEL", "CANAL", "CAPER", "CARGO", "CARRY", "CATCH", "CATER",
  "CAUSE", "CEDAR", "CHAFE", "CHAIN", "CHAIR", "CHALK", "CHANT", "CHASE",
  "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHESS", "CHEST", "CHIEF", "CHILD",
  "CHILL", "CHIMP", "CHOIR", "CHOKE", "CHORE", "CHOSE", "CIGAR", "CIVIC",
  "CIVIL", "CLACK", "CLAIM", "CLAMP", "CLANG", "CLANK", "CLASH", "CLASP",
  "CLASS", "CLEAN", "CLEAR", "CLIMB", "CLING", "CLOAK", "CLOCK", "CLONE",
  "CLOSE", "CLOTH", "CLOUD", "CLOUT", "CLOVE", "CLOWN", "CLUCK", "CLUMP",
  "CLUNK", "COILS", "COMET", "COMIC", "COPSE", "CORAL", "COUCH", "COUGH",
  "COUNT", "COURT", "COVER", "COVET", "CRACK", "CRAFT", "CRANE", "CRASH",
  "CRAVE", "CRAWL", "CREAK", "CREAM", "CREED", "CREEK", "CRIME", "CRIMP",
  "CRISP", "CROOK", "CROSS", "CROWD", "CROWN", "CRUMB", "CRUST", "CRYPT",
  "CUBIC", "CURLS", "CURSE", "CURVE", "CYCLE",

  // D
  "DAISY", "DAILY", "DANCE", "DEBUT", "DECAL", "DECAY", "DECOY", "DELTA",
  "DENIM", "DENSE", "DEPOT", "DERBY", "DIRTY", "DISCO", "DITCH", "DIZZY",
  "DODGE", "DOUGH", "DOWNY", "DRAFT", "DRAIN", "DRAMA", "DRAPE", "DRAWL",
  "DRAWN", "DREAD", "DREAM", "DRESS", "DRIED", "DRIFT", "DRINK", "DROOP",
  "DROVE", "DRUNK", "DRYER", "DUCHY", "DUSKY", "DWARF", "DWELL", "DYING",

  // E
  "EAGER", "EAGLE", "EARLY", "EARTH", "EBONY", "EIGHT", "ELBOW", "EMBED",
  "EMPTY", "ENACT", "ENTER", "ENTRY", "ENVOY", "ERUPT", "ESSAY", "ETHOS",
  "EVADE", "EVENT", "EVICT", "EXACT", "EXALT", "EXCEL", "EXERT", "EXILE",
  "EXIST", "EXPEL", "EXTRA", "EXUDE", "EXULT",

  // F
  "FABLE", "FACET", "FAINT", "FAIRY", "FAITH", "FALSE", "FANCY", "FAUNA",
  "FAVOR", "FEAST", "FEIGN", "FIELD", "FIEND", "FIERY", "FIFTH", "FIGHT",
  "FILCH", "FLAIR", "FLAME", "FLANK", "FLARE", "FLASH", "FLASK", "FLESH",
  "FLEET", "FLIRT", "FLOCK", "FLOOD", "FLOOR", "FLOSS", "FLOUT", "FLOWN",
  "FLUSH", "FLUTE", "FLYER", "FOCUS", "FOGGY", "FOLIO", "FORCE", "FORGE",
  "FOYER", "FRAIL", "FRANK", "FRAUD", "FREAK", "FRESH", "FRONT", "FROTH",
  "FROZE", "FRUIT", "FULLY", "FUNGI", "FUNNY",

  // G
  "GAMUT", "GAUZE", "GAVEL", "GHOST", "GIDDY", "GIVEN", "GIZMO", "GLAND",
  "GLAZE", "GLEAM", "GLEAN", "GLOAT", "GLOOM", "GLORY", "GLOSS", "GLOVE",
  "GLYPH", "GNASH", "GOOSE", "GORGE", "GRACE", "GRADE", "GRAIL", "GRAIN",
  "GRAND", "GRANT", "GRAPE", "GRASP", "GRATE", "GRAVE", "GRAZE", "GREED",
  "GREEN", "GREET", "GRIEF", "GRILL", "GRIME", "GRIND", "GRIPE", "GROAN",
  "GROIN", "GROOM", "GROSS", "GROVE", "GROWL", "GROUT", "GRUEL", "GRUMP",
  "GUARD", "GUAVA", "GUESS", "GUILE", "GUILD", "GUISE", "GUSTO", "GUTSY",
  "GYPSY",

  // H
  "HABIT", "HALVE", "HANDY", "HAPPY", "HARSH", "HASTY", "HASTE", "HATCH",
  "HAVEN", "HAZEL", "HEART", "HEAVE", "HEAVY", "HEDGE", "HEFTY", "HEIST",
  "HELIX", "HELLO", "HENCE", "HERBS", "HERON", "HIPPY", "HITCH", "HOARD",
  "HOMER", "HONEY", "HONOR", "HORSE", "HOTEL", "HOVER", "HOUND", "HOWDY",
  "HUMAN", "HUMID", "HUMOR", "HUNCH", "HURRY", "HUSKY", "HYDRA", "HYENA",
  "HYPER",

  // I
  "IDEAL", "IDIOM", "IDIOT", "IMPLY", "INANE", "INEPT", "INFER", "INGOT",
  "INPUT", "IRONY",

  // J
  "JAUNT", "JAZZY", "JELLY", "JOKER", "JOUST", "JUDGE", "JUICE", "JUICY",
  "JUMPY",

  // K
  "KAYAK", "KHAKI", "KNACK", "KNAVE", "KNEEL", "KNELT", "KNIFE", "KNOCK",
  "KNOLL", "KNOWN", "KOALA", "KUDOS",

  // L
  "LABEL", "LADLE", "LANCE", "LANKY", "LAPEL", "LASER", "LATCH", "LATIN",
  "LATHE", "LATTE", "LARVA", "LAYER", "LEACH", "LEAFY", "LEAPT", "LEAKY",
  "LEASH", "LEAST", "LEMON", "LIGHT", "LILAC", "LIMIT", "LINER", "LINGO",
  "LIVER", "LLAMA", "LODGE", "LOGIC", "LOFTY", "LOOSE", "LOOPY", "LOVER",
  "LOWLY", "LOYAL", "LUCID", "LUNAR", "LUNCH", "LURID", "LUSTY", "LYRIC",

  // M
  "MAGIC", "MANGO", "MANOR", "MANLY", "MAPLE", "MARSH", "MATCH", "MAUVE",
  "MAXIM", "MEALY", "MEATY", "MEDAL", "MERCY", "MELEE", "METAL", "MICRO",
  "MIGHT", "MIMIC", "MINCE", "MISTY", "MIXED", "MOCHA", "MOGUL", "MOIST",
  "MOLDY", "MONEY", "MOODY", "MOOSE", "MORAL", "MOSSY", "MOTIF", "MOUNT",
  "MOUTH", "MOURN", "MOVIE", "MUDDY", "MULCH", "MURAL", "MERRY", "MUTED",

  // N
  "NAIVE", "NASTY", "NAVAL", "NAVEL", "NEEDY", "NERVE", "NERVY", "NIECE",
  "NIGHT", "NIFTY", "NINJA", "NOBLE", "NOISY", "NORTH", "NOTCH", "NOVEL",
  "NUDGE", "NUTTY", "NYMPH",

  // O
  "OAKEN", "OASIS", "OBESE", "OCCUR", "OCEAN", "OFFER", "OFTEN", "OLIVE",
  "ONSET", "OPTIC", "ORATE", "ORBIT", "ORDER", "OUGHT", "OUTDO", "OVATE",
  "OVOID", "OXIDE", "OZONE",

  // P
  "PADDY", "PANSY", "PARTY", "PASTA", "PASTY", "PATCH", "PATIO", "PATSY",
  "PEACE", "PEACH", "PEARL", "PENAL", "PERCH", "PERKY", "PETAL", "PETTY",
  "PHASE", "PHONE", "PHOTO", "PIANO", "PILOT", "PINCH", "PINTO", "PIVOT",
  "PIXEL", "PIXIE", "PIZZA", "PLACE", "PLAID", "PLAIN", "PLANK", "PLANT",
  "PLAZA", "PLIER", "PLUCK", "PLUMB", "PLUME", "PLUNK", "PLUSH", "POACH",
  "POISE", "POLYP", "POPPY", "PORCH", "PRANK", "PREEN", "PRESS", "PRIME",
  "PRIVY", "PROBE", "PRONE", "PRONG", "PROUD", "PROWL", "PRUDE", "PRUNE",
  "PROXY", "PSALM", "PUBIC", "PUDGY", "PULPY", "PUNCH", "PUPPY", "PURSE",
  "PUSHY",

  // Q
  "QUACK", "QUAFF", "QUAIL", "QUAKE", "QUALM", "QUEEN", "QUERY", "QUEUE",
  "QUIRK", "QUITE", "QUOTA", "QUOTE",

  // R
  "RABBI", "RABID", "RACER", "RADAR", "RAINY", "RALLY", "RANCH", "RANGE",
  "RAPID", "RASPY", "RAVEN", "REACH", "REALM", "REBEL", "REBUS", "RECUT",
  "REEDY", "REFER", "REGAL", "REIGN", "RELAY", "RELIC", "REMIT", "REPAY",
  "REPEL", "RIDER", "RIGID", "RISEN", "RISKY", "RIVAL", "RIVET", "ROAST",
  "ROBIN", "ROCKY", "ROOMY", "ROUGE", "ROUGH", "ROUSE", "ROVER", "ROWDY",
  "ROYAL", "RUDDY", "RUGBY", "RULER", "RUSTY",

  // S
  "SAINT", "SALAD", "SALLY", "SALTY", "SAUCE", "SAUNA", "SAVVY", "SCALD",
  "SCALP", "SCAMP", "SCANT", "SCARE", "SCARF", "SCARY", "SCENE", "SCONE",
  "SCOOP", "SCORE", "SCORN", "SCOUT", "SCOWL", "SCRAM", "SCRAP", "SCREW",
  "SCRUB", "SHADE", "SHADY", "SHAKE", "SHALL", "SHAME", "SHANK", "SHAPE",
  "SHARE", "SHARK", "SHARP", "SHAWL", "SHEEN", "SHEET", "SHEEP", "SHELF",
  "SHELL", "SHEER", "SHIFT", "SHINE", "SHINY", "SHIRT", "SHOCK", "SHONE",
  "SHORE", "SHORT", "SHOUT", "SHOVE", "SHRUB", "SHUNT", "SHUSH", "SIEGE",
  "SIEVE", "SILKY", "SILLY", "SINCE", "SISSY", "SIXTH", "SIXTY", "SKULL",
  "SLANG", "SLANT", "SLEEK", "SLEEP", "SLEET", "SLICK", "SLIDE", "SLIME",
  "SLIMY", "SLOPE", "SLOSH", "SLOTH", "SLUMP", "SLURP", "SMACK", "SMALL",
  "SMART", "SMASH", "SMEAR", "SMELL", "SMIRK", "SNACK", "SNAKE", "SNARE",
  "SNARL", "SNEAK", "SNEER", "SNIDE", "SNIFF", "SNOOP", "SNORE", "SNORT",
  "SNOWY", "SOAPY", "SOBER", "SOLID", "SOLVE", "SONIC", "SORRY", "SOUTH",
  "SPACE", "SPADE", "SPARE", "SPARK", "SPAWN", "SPEAK", "SPEAR", "SPECK",
  "SPEED", "SPELL", "SPEND", "SPICE", "SPICY", "SPILL", "SPINE", "SPITE",
  "SPLIT", "SPOKE", "SPOOK", "SPOON", "SPORE", "SPORT", "SPOUT", "SPUNK",
  "SQUAD", "SQUAT", "SQUID", "STACK", "STAIN", "STAIR", "STAKE", "STALE",
  "STALL", "STAMP", "STAND", "STANK", "STARE", "START", "STARK", "STASH",
  "STATE", "STAVE", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STERN",
  "STICK", "STIFF", "STILL", "STING", "STINK", "STOIC", "STOMP", "STONE",
  "STONY", "STORE", "STORM", "STORY", "STOVE", "STRAP", "STRAW", "STRAY",
  "STRIP", "STRUT", "STUDY", "STUCK", "STUMP", "STUNK", "STUNT", "SURGE",
  "SWAMP", "SWEAR", "SWEAT", "SWEEP", "SWEET", "SWIFT", "SWILL", "SWIPE",
  "SWIRL", "SWOON", "SWORE", "SWORN", "SYRUP",

  // T
  "TABBY", "TACKY", "TAFFY", "TALLY", "TALON", "TANGY", "TAPIR", "TAROT",
  "TARDY", "TAUNT", "TAWNY", "TEACH", "TEASE", "TEMPO", "TENSE", "TEMPT",
  "TEPID", "TERSE", "TESTY", "THANK", "THICK", "THIRD", "THROB", "THORN",
  "THREE", "THREW", "THROE", "THROW", "THUMB", "THUMP", "TIARA", "TIGER",
  "TIGHT", "TIMER", "TIMID", "TIPSY", "TITAN", "TITLE", "TOAST", "TODAY",
  "TOKEN", "TONAL", "TONIC", "TORSO", "TOUCH", "TOUGH", "TOWEL", "TOXIC",
  "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAMP", "TRAIT", "TRASH",
  "TRAWL", "TREAD", "TREAT", "TREND", "TRIAD", "TRIBE", "TRIED", "TRIPE",
  "TRITE", "TROLL", "TROOP", "TROTH", "TROUT", "TROVE", "TRUCE", "TRUCK",
  "TRULY", "TRUMP", "TRYST", "TULIP", "TUMMY", "TUNER", "TUNIC", "TUTOR",
  "TWANG", "TWEED", "TWERP", "TWICE", "TWIRL", "TYING",

  // U
  "ULCER", "ULTRA", "UNCLE", "UNCUT", "UNDUE", "UNFIT", "UNITY", "UNTIL",
  "UNZIP", "UPSET", "URBAN", "USHER", "UTTER",

  // V
  "VAGUE", "VALID", "VALOR", "VALUE", "VALVE", "VAULT", "VAUNT", "VENOM",
  "VERSE", "VICAR", "VIPER", "VISOR", "VISTA", "VITAL", "VIVID", "VOCAL",
  "VODKA", "VOGUE", "VOICE", "VEXED",

  // W
  "WACKY", "WAGON", "WAIST", "WALTZ", "WASTE", "WATCH", "WATER", "WAVER",
  "WEARY", "WEAVE", "WEDGE", "WEIGH", "WEIRD", "WHALE", "WHEAT", "WHEEL",
  "WHERE", "WHICH", "WHILE", "WHIFF", "WHINE", "WHISK", "WHITE", "WHOLE",
  "WHOSE", "WIDER", "WIELD", "WINDY", "WITTY", "WOKEN", "WOODY", "WORDY",
  "WORLD", "WORMY", "WORST", "WORTH", "WOOZY", "WOUND", "WRATH", "WRING",
  "WRIST", "WRONG", "WROTE",

  // Y
  "YACHT", "YEARN", "YEAST", "YIELD", "YOUNG", "YOUTH", "YUCKY",

  // Z
  "ZESTY", "ZILCH", "ZIPPY", "ZOMBIE",
];
